TYPO3-Documentation/TYPO3CMS-Reference-Typoscript

- Documentation/Functions/HtmlparserTags/Index.rst
Please **do not merge** before https://review.typo3.org/#/c/30935/ has passed the review system.
Document the new behavior of the HTMLparser_tags userFunc configuration that is introduced with #59712 and enhance the documentation of method parameters and the return value.
Resolves: #64201
Relates: #59712
> [TASK] HTMLparser_tags userFunc custom parameters

- Documentation/Conditions/Reference/Index.rst
I believe there is a mistake in the way the condition on remote host is described.
> Host cannot be detected using REMOTE_ADDR

- Documentation/Gifbuilder/ObjectNames/Index.rst
Add a short explanation of what solarize does, document what the value for the effect means.
Resolves: #26064
> [TASK] Add more documentation to GIFBUILDER solarize effect

- Documentation/Setup/Top-levelObjects/Index.rst
This property has been removed
> Remove reference to top level object includeLibs

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Make TYPO3 integrators happy again
> [BUGFIX] Fix missing char in variables section

- Documentation/Setup/Meta/Index.rst
Make it clear how to use stdWrap for defining meta tags
with a very common example.
> [TASK] Add short example for stdWrap usage

- Documentation/Conditions/Index.rst
Check, if a value is empty or is not empty with regular expression.
> How to check empty or not empty

- Documentation/ContentObjects/Image/Index.rst
See https://forge.typo3.org/issues/75255
> Fix layoutKey docs

- Documentation/Gifbuilder/ObjectNames/Index.rst
the description of the property "antiAlias" has been updated with the informations contained on the issue: https://forge.typo3.org/issues/17185
> [TASK] Restriction for antiAlias of GIFBUILDER

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Please prettify the change as much as possible, I cannot remember the rest syntax. :-X
> [TASK] Document relevance of controllerExtensionName for translations

- Documentation/Functions/Imgresource/Index.rst
With feature #65584 a option to define a custom crop setting was added to the imgResource object
https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.2/Feature-65584-AddImageCropping.html
> [TASK] Document crop option of imgResource

- Documentation/Conditions/Reference/Index.rst
Use class for a userFunc in condition.
> Change to class name in userFunc condition

- Documentation/Setup/Config/Index.rst
Change in Cache-control header value related to https://review.typo3.org/#/c/54788/
> #54788 Cache-control header value change

- Documentation/ContentObjects/Hmenu/Index.rst
"default" values block is rendered in the wrong position; plus: streamline of default boolean values to "0 (false)"
> change position of default block

- Documentation/ContentObjects/Hmenu/Index.rst
Added some examples for better undersrtanding of entryLevel property; solves https://forge.typo3.org/issues/81229
> better explanation of entryLevel property

- Documentation/ContentObjects/UserAndUserInt/Index.rst
Modified layout for properties to make them consistent with the other parts of documentation; please review
> Use "Table" layout for properties

- Documentation/ContentObjects/Fluidtemplate/Index.rst
We must encourage people to use site extensions.
> [TASK] Replace fileadmin by site extension

- Documentation/MenuObjects/CommonProperties/Index.rst
- Documentation/Setup/Config/Index.rst
- Documentation/Setup/Constants/Index.rst
- Documentation/Setup/Page/Index.rst
Add semantic markup like code.
Add internal references, for easier navigation.
> TASK: Small fixes

- Documentation/Conditions/Reference/Index.rst
- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/DataTypes/Gettext/Index.rst
- Documentation/Functions/Imgresource/Index.rst
- Documentation/Gifbuilder/ObjectNames/Index.rst
- Documentation/ObjectsAndProperties/OptionSplit/Index.rst
- Documentation/Setup/Config/Index.rst
suggestion for improvement of spelling and grammar
> spelling and grammar mistakes

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Feature description plus minor fixes
https://github.com/TYPO3/TYPO3.CMS/edit/master/typo3/sysext/core/Documentation/Changelog/master/Feature-84650-IntroduceLanguageMenuProcessor.rst
> Feature: #84650 - Introduce fluid data processor for language menus

- Documentation/Functions/If/Index.rst
Thinking positively is easier than thinking negatively.
> write it in the positive way

- Documentation/Conditions/Index.rst
It is hard to guess that TypoScript has another form of conditions.
> under If there are more conditions

- Documentation/ContentObjects/LoadRegister/Index.rst
see https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Stdwrap/Index.html
What does "special entry" mean?
> field mus be a text

- Documentation/MenuObjects/Tmenuitem/Index.rst
In the description of the menu item you want the page which comes from the menu item by the loop coming from TMENU. You do not want the current page of the website here.
> menu item page

- Documentation/DataTypes/Properties/GetText.rst.txt
It should be described, how to use $GLOBALS['TYPO3_CONF_VARS']['FE']['addRootLineFields']
> Add detailed information to use levelfield

- Documentation/ContentObjects/Svg/Index.rst
> Remove value and noscript options of CE SVG

- Documentation/ContentObjects/Svg/Index.rst
> Remove value and noscript options of CE SVG (9.5)

- Documentation/Functions/Typolink.rst
* [TASK] Add missing t3:// link handlers
* [BUGFIX] Use correct ampersand encoding in URL
> [TASK] Add missing t3:// link handlers (#216)

- Documentation/Functions/Imagelinkwrap.rst
Resolves: #225
Releases: master, 9.5
> Add Header for imageLinkWrap

- Documentation/Setup/Top-levelObjects/Index.rst
Open for a discussion how to make it more verbose from the menu and manual content what this property is about.
> Propose a more understandable name for a page object

- Documentation/ObjectsAndProperties/Calc/Index.rst
> Improve +calc description

- Documentation/ContentObjects/Case/Index.rst
- Documentation/ContentObjects/CoaAndCoaInt/Index.rst
- Documentation/ContentObjects/Content/Index.rst
- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/ContentObjects/Records/Index.rst
- Documentation/ContentObjects/Text/Index.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/DataTypes/Properties/Cache.rst.txt
solves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/237
> Include Cache property to cObjects

- Documentation/MenuObjects/Jsmenu/Index.rst
- Documentation/MenuObjects/Jsmenuitem/Index.rst
Resolves: https://github.com/TYPO3-Documentation/T3DocTeam/issues/108
> Add note for removal of JSMENU / JSMENUITEM in 9

- Documentation/Index.rst
As already for the other manuals
> Move sitemap to end of menu

- Documentation/Setup/Page/Index.rst
* Set block "same as includeJS" to section "includeJSFooter" as well
* Add short descriptions of what the difference is between all "includeJSxxx" sections
* Move example in "includeJSFooter" to "includeJS"
> Clarify inclusion of JavaScript

- Documentation/ContentObjects/File/Index.rst
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/108
Releases: master
> Remove content object File

- Documentation/Functions/Typolink.rst
I added a title for the target property; please review
> [BUGFIX] add missing title for target property

- Documentation/Functions/Typolink.rst
It is very hard to find out, how to get a link and have not a tags around it.
> give a hint about a link without html a tags

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Resolves: #272
Releases: master, 9.5
> Fix formatting on FLUIDTEMPLATE page

- Documentation/Conditions/Index.rst
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/60637
Releases: master, 9.5
> [TASK] Add getPageArguments() to request in conditions

- Documentation/ContentObjects/Hmenu/Index.rst
Related TYPO3 core patch master (10.4.0-dev): https://review.typo3.org/c/Packages/TYPO3.CMS/+/64183
Related TYPO3 core patch backport (9.5): https://review.typo3.org/c/Packages/TYPO3.CMS/+/64149
> Add info about stdWrap functionality of includeNotInMenu

- Documentation/Functions/Select.rst
See https://github.com/TYPO3/TYPO3.CMS/blob/a26680bf6effa4cf45c574bc5f0f2c5943364816/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php#L843
> [TASK] Document pidInList=0

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Previous explanation only referred to TEMPLATE and provided no explanation for
beginners.
Resolves: #258
> Update introduction for FLUIDTEMPLATE

- Documentation/ContentObjects/Fluidtemplate/Index.rst
- use automatically generated toc for properties
> Change content overview for FLUIDTEMPLATE properties

- Documentation/Functions/Typolink.rst
Remove remaining reference in Functions/Typolink
Resolves: #339
Related: #320 
Releases: master, 10.4
> Remove reference to config.ftu

- Documentation/Functions/Select.rst
Related: https://forge.typo3.org/issues/87799
Resolves: #352
Releases: master, 10.4, 9.5, 8.7
> Point out problem with select markers and orderBy

- Documentation/Functions/Select.rst
Resolves: #354
Releases: master, 10.4, 9.5, 8.7
> Quote fields in select.where etc.

- Documentation/MenuObjects/Sectionindex/Index.rst
- Documentation/Setup/Config/Index.rst
See Core Deprecation 84637
Resolves: #359
> [TASK] Remove linkData references

- Documentation/Setup/Page/Index.rst
- Documentation/TopLevelObjects/Plugin.rst
see Deprecation 85822
see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/850
> [TASK] Replace PageGenerator references

- Documentation/Functions/Typolink.rst
see Feature 86629 
see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/849
> [TASK] Add telephone link handler

- Documentation/Functions/If.rst
Resolves #348
See Core Feature 90213
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/845
> [FEATURE] Add bitAnd to if

- Documentation/UsingSetting/Entering.rst
See Core Important 89720
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/845
Resolves #349
> [TASK] Add hint about importing legacy TS files

- Documentation/UsingSetting/Constants.rst
See Core Feature 91080
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/841
> [FEATURE] Add Constant Loading Order

- Documentation/Functions/Typolink.rst
See Core Feature 86365
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/849
> [TASK] Remove "useCacheHash" from docs

- Documentation/Setup/Config/Index.rst
can be backported to older branches
> Improve description of the config.no_cache

- Documentation/Conditions/Index.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-88276-TypoScriptConditionForPageLayout.html
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
> Add condition for page layout

- Documentation/About.rst
See https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/187
> Fix invalid links to Forger

- Documentation/ContentObjects/UserAndUserInt/Index.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92984-PSR-7RequestAvailableInFrontendContentObjects.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
> [FEATURE] PSR-7 Request in Content Objects

- Documentation/ContentObjects/Fluidtemplate/DataProcessing.rst
merge into 10.4, cherry-pick into master
resolves #338
> Feature: 78347 - Add StdWrap properties to FilesProcessor (10.3)

- Documentation/Functions/Typolink.rst
merge into master
resolves #341
> Breaking: 88755 - Remove POST option from addQueryString version 11

- Documentation/Setup/Config/Index.rst
merge into master; cherry pick into 10.4
resolves #342
> Feature: 83734 - Add support for current page in config.cache (10.0)

- Documentation/ContentObjects/Fluidtemplate/Index.rst
resolves #314
preport to master
I accidently commited this to 9.5. If there are change requests they also need to be merged into 9.5
> How to use template in FLUIDTEMPLATE with property template

- Documentation/DataTypes/Properties/GetText.rst.txt
- Documentation/Functions/Cache.rst
resolves #288
preport to master
> Remove all references to the removed configurations

- Documentation/ContentObjects/Template/Index.rst
> TEMPLATE without FILE 

- Documentation/Setup/Page/Index.rst
(10.2)
Merge in 10.4; Cherry-Pick into Master
resolves #344
> Feature: 86759 - Support nomodule attribute for JavaScript includes

- Documentation/Setup/Config/Index.rst
- Documentation/Setup/Page/Index.rst
Merge into 10.4, cherrypick into master
resolves #343
> Feature: 88648 - Override Twitter Card Type with TypoScript

- Documentation/ContentObjects/LoadRegister/Index.rst
- Documentation/ContentObjects/Records/Index.rst
- Documentation/TopLevelObjects/Plugin.rst
resolves #256
backport to 9.5 and 10.4
> Remove references to css styled content

- Documentation/Conditions/Index.rst
> Add example for applicationContext

- Documentation/Conditions/Index.rst
> Properly match prefix for applicationContext

- Documentation/ContentObjects/GeneralInformation/Index.rst
Add reST syntax to inline-code
Releases: 10.4, 9.5
> Add reST syntax to inline-code

- Documentation/Functions/OptionSplit.rst
> Resolve #247 chapter optionsplit

- Documentation/Setup/Page/Index.rst
Backport: 10.4, 9.5
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/154
> Wiki Migration: Add_your_own_favicon

- Documentation/ContentObjects/Fluidtemplate/DataProcessing.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
See Core Issue #89509
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1303
> [FEATURE] Add FlexFormProcessor

- Documentation/Setup/Config/Index.rst
Based on changes in https://review.typo3.org/c/Packages/TYPO3.CMS/+/67930. Should only get merged after this patch is merged.
> [WIP] Add documentation about config.disableHrefLang

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
> Reference HMENU from the MenuProcessor

- Documentation/ContentObjects/Hmenu/Index.rst
Releases master, 10.4, 9.5
@resolves 271
> Mention DataProcessors in HMNU

- Documentation/Gifbuilder/Examples.rst
- Documentation/Gifbuilder/Index.rst
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/154
Releases: master, 10.4, 9.5
> Wiki Migration: GIFBULDER Examples

- Documentation/Setup/Config/Index.rst
Based on the newly introduced setting in https://review.typo3.org/c/Packages/TYPO3.CMS/+/68258
> [TASK] Add config.disableCanonical

- Documentation/DataTypes/Properties/GetText.rst
> Add recursive example for gettext DB

- Documentation/Settings.cfg
- Documentation/Setup/Page/Examples.rst
- Documentation/Setup/Page/Index.rst
> [Feature] Examples about PAGE objects as ajax / json

- Documentation/Functions/Stdwrap.rst
Add link to date format.
Releases: master, 10.4, 9.5, 8.7
> https for php.net page

- Documentation/Functions/Stdwrap.rst
> link for createfromformat

- Documentation/Conditions/Index.rst
For better understanding how to make conditions with it
> Update of page array example

- Documentation/Functions/Imgresource.rst
> Fix link to crop variants

- Documentation/DataTypes/Properties/GetText.rst
relates https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395
> Deprecation: #94165 - sys_language table

- Documentation/UsingSetting/TheConstantEditor.rst
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.
> [TASK] Update TYPO3 repository URL

- Documentation/ContentObjects/Editpanel/Index.rst
- Documentation/Functions/Stdwrap.rst
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
> [Deprecation] #94953 - Edit panel related frontend functionality

- Documentation/Functions/Stdwrap.rst
Update wording and draw attention.
> Refresh development warning for stdWrap debug options

- Documentation/ContentObjects/Fluidtemplate/Index.rst
> Explain Data available in Fluid templates

- Documentation/ContentObjects/Fluidtemplate/Index.rst
> FLUIDTEMPLATE has replaced    TEMPLATE

- Documentation/Gifbuilder/ObjectNames/Index.rst
> [DOCS] Add default value for tiles

- Documentation/Gifbuilder/ObjectNames/Index.rst
> [BUGFIX] Set correct default value for XY

- Documentation/Gifbuilder/ObjectNames/Index.rst
> [TASK] Add range for XY

- Documentation/Conditions/Index.rst
- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/Functions/Makelinks.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Setup/Config/Index.rst
- Documentation/Setup/Page/Index.rst
See TYPO3-Documentation/T3DocTeam#165 for details.
> [TASK] Unify top-level domain of dummy urls

- Documentation/Conditions/Index.rst
See TYPO3-Documentation/T3DocTeam#165 for details.
> [TASK] Replace `example.local` with `example.localhost`

- .editorconfig
- Documentation/Conditions/Index.rst
- Documentation/ContentObjects/Image/Index.rst
- Documentation/DataTypes/Index.rst
- Documentation/DataTypes/Properties/GetText.rst.txt
- Documentation/Functions/HtmlparserTags.rst
- Documentation/Functions/Imagelinkwrap.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Typolink.rst
- Documentation/Index.rst
- Documentation/Settings.cfg
- Documentation/Setup/Config/Index.rst
- Documentation/Setup/Page/Index.rst
See TYPO3-Documentation/T3DocTeam#166 for details.
> [TASK] Unify placeholder syntax

- Documentation/Functions/Imagelinkwrap.rst
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/171
releases: main, 11.5, 10.4, 9.5, 8.7, 7.6
> [TASK] fix link to api

- Documentation/Functions/Select.rst
> Fix indentation on code-block

- Documentation/Functions/GetEnv.rst
Additionally, format lines for better code readability.
> [TASK] Mention dotenv implementations

- Documentation/Setup/Config/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/98
> [FEATURE] #97653 - Add option to influence display of the website title

- Documentation/TopLevelObjects/Module.rst
Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/18
> Feature: #97096 - Non-namespaced arguments in extbase backend modules

- Documentation/Functions/Stdwrap.rst
Resolves: #504
Releases: main, 11.5, 10.4
> [TASK] #94484 - Introduce HTML Sanitizer

- Documentation/Conditions/Index.rst
- Documentation/Functions/Encapslines.rst
- Documentation/Functions/HtmlparserTags.rst
- Documentation/Functions/If.rst
- Documentation/Functions/Imgresource.rst
- Documentation/Functions/Makelinks.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Replacement.rst
- Documentation/Functions/Select.rst
- Documentation/Functions/Split.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Tags.rst
- Documentation/Functions/Typolink.rst
Additionally, adjust indentation of some code examples
> [TASK] Remove quote around examples

- Documentation/Conditions/Index.rst
See https://typo3.slack.com/archives/C025BQLFA/p1656186317720129
> Use traverse as page might not be set in CLI or BE context

- Documentation/Setup/Page/Index.rst
Releases: main, 11.5, 10.4
Resolves: #457
> [TASK] Add properties to includeJSlibs and includeJSFooterlibs

- Documentation/DataTypes/Properties/GetText.rst
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/117
> Deprecation: #97866 - Various public TSFE properties

- Documentation/ContentObjects/Svg/Index.rst
- Documentation/ContentObjects/Text/Index.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
> Unify the layout of the rest of the Content objects

- Documentation/DataTypes/Index.rst
- Documentation/Functions/Cache.rst
- Documentation/Functions/Data.rst
- Documentation/Functions/Encapslines.rst
- Documentation/Functions/Htmlparser.rst
- Documentation/Functions/HtmlparserTags.rst
> [TASK] Unify headline structure of functions

- Documentation/UsingSetting/TheConstantEditor.rst
This type does not make any sense whatsoever and
shouldn't be documented.
> [TASK] Avoid 'comment' type

- Documentation/Functions/Imagelinkwrap.rst
so it is the same like in the other functions
> [TASK] Unify structure of Imagelinkwrap

- Documentation/Functions/Htmlparser.rst
- Documentation/Functions/If.rst
- Documentation/Functions/Imgresource.rst
- Documentation/Functions/Makelinks.rst
- Documentation/Functions/Numberformat.rst
- Documentation/Functions/Numrows.rst
- Documentation/Functions/OptionSplit.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Replacement.rst
- Documentation/Functions/Round.rst
- Documentation/Functions/Select.rst
- Documentation/Functions/Split.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Strpad.rst
- Documentation/Functions/Tags.rst
- Documentation/Functions/Typolink.rst
so it is the same like in the other functions
> [TASK] Unify structure of Tyoscript functions

- Documentation/TopLevelObjects/Plugin.rst
references: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/171
releases: main
> [TASK] Make the AbstractPlugin @internal

- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/Settings.cfg
- Documentation/Setup/Page/Examples.rst
- Documentation/UsingSetting/AccessTypoScriptWithExtensions.rst
> [TASK] Remove references to the extbase book

- Documentation/Functions/Typolink.rst
- composer.json
Related: TYPO3-Documentation/Changelog-To-Doc#191
> [TASK] #98443 - Extension recordlist merged into backend

- Documentation/Functions/Data.rst
> [BUGFIX] Avoid quote style in example

- Documentation/Setup/Page/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/222
> [FEATURE] #91499 - Additional attributes for includeJS, includeCSS, etc.

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
> [TASK] Revise chapter "DatabaseQueryProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/CommaSeparatedValueProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
> [TASK] Revise chapter "CommaSeparatedValueProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SplitProcessor.rst
> [TASK] Revise chapter "SplitProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
> [TASK] Revise chapter "FilesProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
> [TASK] Revise chapter "FlexFormProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
> [TASK] Revise chapter "GalleryProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/LanguageMenuProcessor.rst
> [TASK] Revise chapter "LanguageMenuProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
> [TASK] Revise chapter "MenuProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteProcessor.rst
> [TASK] Revise chapter "SiteProcessor"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteLanguageProcessor.rst
> [TASK] Revise chapter "SiteLanguageProcessor"

- Documentation/AppendixA/Index.rst
> [TASK] Revise TSFE section

- Documentation/Setup/Page/Index.rst
> [BUGFIX] Fix code example indentation

- Documentation/Functions/Typolink.rst
- Documentation/Setup/Config/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/251
> [FEATURE] #87919 - Allow generation of absolute URLs completely

- Documentation/Setup/Config/Index.rst
> [BUGFIX] Remove forgotten disableImgBorderAttr property in table

- Documentation/Functions/If.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/274
> [FEATURE] #99194 - Extend stdWrap.if feature

- Documentation/About.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/GeneralInformation/Index.rst
- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/DataTypes/Index.rst
- Documentation/Functions/Calc.rst
- Documentation/Functions/Imagelinkwrap.rst
- Documentation/Functions/OptionSplit.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Split.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Typolink.rst
- Documentation/Gifbuilder/ObjectNames/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/Setup/Config/Index.rst
Inspired by: https://twitter.com/marcelpociot/status/1594706393696985088
Also, some of the usages are just fillers which does not convey meaning.
> [TASK] Remove "simply" and "just" where not appropriate

- Documentation/About.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/GeneralInformation/Index.rst
- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/DataTypes/Index.rst
- Documentation/Functions/Calc.rst
- Documentation/Functions/Imagelinkwrap.rst
- Documentation/Functions/OptionSplit.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Split.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Typolink.rst
- Documentation/Introduction/Index.rst
- Documentation/Setup/Config/Index.rst
Inspired by: https://twitter.com/marcelpociot/status/1594706393696985088
Also, some of the usages are just fillers which does not convey meaning.
> [TASK] Remove "simply" and "just" where not appropriate (#651)

- Documentation/Functions/Parsefunc.rst
- Documentation/TopLevelObjects/Constants.rst
- Documentation/UsingSetting/Constants.rst
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/256
> [TASK] Deprecate TypoScript setup "constants" TLO

- Documentation/Setup/Config/Index.rst
This is also added to main with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/656.
Releases: 11.5
> [TASK] Add note to config.baseURL

- Documentation/Setup/Config/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/276
> [DEPRECATION] #99170 - config.baseURL

- Documentation/Functions/If.rst
> [TASK] Sort properties of "if" function

- Documentation/ContentObjects/Case/Index.rst
- Documentation/Settings.cfg
references #658, https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/310
> [TASK] Introduce custom confval directive for cObj CASE

- Documentation/ContentObjects/Case/Index.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/CommaSeparatedValueProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/LanguageMenuProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteLanguageProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SplitProcessor.rst
- Documentation/Settings.cfg
This also removes the warnings about duplicate confval names
references #658, https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/310
> [TASK] Introduce custom confval directive for Data Processors

- Documentation/ContentObjects/CoaAndCoaInt/Index.rst
- Documentation/Settings.cfg
references #658, https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/310
> [TASK] Introduce custom confval directive for cObj COA

- Documentation/ContentObjects/Case/Index.rst
- Documentation/ContentObjects/CoaAndCoaInt/Index.rst
- Documentation/ContentObjects/Text/Index.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Settings.cfg
references #658, https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/310
> [TASK] Introduce custom confval directive for cObj TEXT

- Documentation/DataTypes/Index.rst
- Documentation/Functions/Cache.rst
- Documentation/Functions/Encapslines.rst
- Documentation/Functions/Htmlparser.rst
- Documentation/Functions/HtmlparserTags.rst
- Documentation/Functions/If.rst
- Documentation/Functions/Imagelinkwrap.rst
- Documentation/Functions/Imgresource.rst
- Documentation/Functions/Makelinks.rst
- Documentation/Functions/Numberformat.rst
- Documentation/Functions/Numrows.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Replacement.rst
- Documentation/Functions/Round.rst
- Documentation/Functions/Select.rst
- Documentation/Functions/Split.rst
- Documentation/Functions/Strpad.rst
- Documentation/Functions/Tags.rst
- Documentation/Settings.cfg
stdWrap and typolink tbd as they are more complex
references #658
> [TASK] Introduce custom confval directive for simpler functions

- Documentation/Functions/Imagelinkwrap.rst
> [BUGFIX] Fix reference in "imageLinkWrap" chapter

- Documentation/Functions/Imagelinkwrap.rst
> [Backport 11.5] [TASK] Fix reference in "imageLinkWrap" chapter (#673)

- Documentation/ContentObjects/Hmenu/Categories.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/Functions/Data.rst
- Documentation/Functions/Encapslines.rst
- Documentation/Functions/Imgresource.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Select.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Settings.cfg
- Documentation/Setup/Config/Index.rst
- Documentation/UsingSetting/Debugging.rst
- Documentation/UsingSetting/Register.rst
> [TASK] Introduce custom confval directive for stdwrap

- Documentation/MenuObjects/Index.rst
- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/MenuObjects/Tmenuitem/Index.rst
- Documentation/Settings.cfg
> [TASK] Introduce custom confval directive for HMENU and HMENU items

- Documentation/Functions/Typolink.rst
- Documentation/Settings.cfg
- Documentation/Setup/Config/Index.rst
Introduce custom confval directive for typolink
references #658
> [TASK] Overhaul typolink chapter

- Documentation/Introduction/Index.rst
- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/Setup/Config/Index.rst
- Documentation/TopLevelObjects/Plugin.rst
> [BUGFIX] Fix rendering errors

- Documentation/Functions/Select.rst
> [TASK] Link to SQL injection chapter in TYPO3 Explained

- Documentation/Setup/Config/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/307
Releases: main
> [FEATURE] #99340 - Add stdWrap properties to config.additionalHeaders

- Documentation/Functions/Select.rst
> [TASK] Link to SQL injection chapter in TYPO3 Explained (#680)

- Documentation/Functions/Typolink.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/212
Releases: main
> [FEATURE] #98488 - Additional setting for Typolink option "addQueryString"

- Documentation/Setup/Config/Index.rst
This reverts commit 73d99cdd2148b31f553f3449e770651338f16209.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/358
Releases: main
> Revert "[FEATURE] #99340 - Add stdWrap properties to config.additionalHeaders (#683)"

- .github/ISSUE_TEMPLATE/config.yml
> [TASK] Add security option to issue templates

- Documentation/Setup/Config/Index.rst
Additionally, adjust "Known properties" in header to just "Properties". It is assumed that there are no "unknown" properties.
See: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Menus/HeadlinesAndSection.html#headlines-and-sections
Releases: main
> [TASK] Adjust header styles in CONFIG chapter

- Documentation/ContentObjects/Extbaseplugin/Index.rst
- Documentation/ContentObjects/Index.rst
- Documentation/Settings.cfg
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/426
Releases: main
> [FEATURE] #100293 -  Introduce cObject for Extbase plugins

- Documentation/Functions/Stdwrap.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/393
Releases: main
> [FEATURE] #100187 - Introduce php-intl based date&time formatting

- Documentation/ContentObjects/Hmenu/Rootline.rst
Additionally:
- Add links
- Use code directives
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/712
> [TASK] Adjust rootline example to use a HTML list

- Documentation/Conditions/Index.rst
Improve ToC, update to current core, improve
examples, add missing data, better introduction.
> [TASK] Restructure condition chapter

- Documentation/Functions/Data.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/255
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2844
Releases: main
> [FEATURE] #99048 - Add siteSettings key for .data

- Documentation/TopLevelObjects/Plugin.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/397
Releases: main
> [FEATURE] #99976 - Introduce ignoreFlexFormSettingsIfEmpty Extbase configuration

- Documentation/Functions/Data.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/464
Releases: main
> [TASK] #94347 - Harmonize site configurations "flag" setting

- Documentation/TopLevelObjects/Module.rst
- Documentation/TopLevelObjects/Plugin.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/455
Releases: main
> [TASK] #100622 - Deprecate Extbase feature toggles

- Documentation/Conditions/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/434
Releases: 11.5
> [TASK] Add note to avoid loginUser and usergroup conditions

- Documentation/Conditions/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/447
Releases: main
> [TASK] #100563 - Using null-safe-operator with getTSFE() function (#734)

- Documentation/Conditions/Index.rst
The descriptive texts are taken from the methods of the NormalizedParams class.
Resolves: #742
> [TASK] Enhance section "request.getNormalizedParams()"

- Documentation/Conditions/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/534
Releases: main
> [TASK] #101053 - Remove deprecated code from ExpressionLanguage

- Documentation/Functions/Data.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/619
Releases: main
> [TASK] #100963 - Adjust hint for now removed TSFE properties

- Documentation/Setup/Config/Index.rst
> [TASK] Adjust data type formatting for config.spamProtectEmailAddresses

- Documentation/Conditions/Index.rst
- Adjust indentations
- Adjust wording
- Move sentence with link about the basic TS syntax in an admonition to make it more prominent
- Add references to TYPO3 Explained where appropriate
- Remove list of available functions for request.getNormalizedParams() in favor of a link to the API to avoid duplications
- Rework siteLanguage section
> [TASK] Revise the conditions chapter

- Documentation/Conditions/Index.rst
- Adjust indentations
- Adjust wording
- Move sentence about the basic TS syntax in an admonition to make more prominent
- Add references to more information where appropriate
- Remove list of available functions for request.getNormalizedParams() in favor of a link to the API to avoid duplications
- Rework siteLanguage section
> [Backport 12.4] [TASK] Revise the conditions chapter (#783)

- Documentation/Gifbuilder/Gifbuilder/Index.rst
- Documentation/Gifbuilder/ObjectNames/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/653
Releases: main
> [TASK] #101941 - Remove GIFBUILDER's reduceColors option

- Documentation/Conditions/Index.rst
Related: https://typo3.slack.com/archives/C025BQLFA/p1695726759085809
> [Backport 11.5] [TASK] Check request object in conditions

- Documentation/Functions/Typolink.rst
What's that half-sentence all about? :joy:
> Fix typo for page.parameters

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/_FlexFormWithFal.xml
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/654
Releases: main
> [Feature] #94501 - FAL support for FlexFormProcessor

- Documentation/Gifbuilder/Gifbuilder/Index.rst
- Documentation/Gifbuilder/Index.rst
> [TASK] Revise Gibuilder/Gifbuilder chapter

- Documentation/Gifbuilder/Gifbuilder/Index.rst
- Documentation/Gifbuilder/Index.rst
> [Backport 12.4] [TASK] Revise Gibuilder/Gifbuilder chapter (#816)

- Documentation/Gifbuilder/Gifbuilder/Index.rst
- Documentation/Gifbuilder/Index.rst
> [Backport 11.5] [TASK] Revise Gibuilder/Gifbuilder chapter (#816)

- Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
- Documentation/Settings.cfg
- Add example for "autoLevels" property
> [Backport 11.5] [TASK] Revise GIFBUILDER object ADJUST (#834)

- Documentation/Gifbuilder/Examples.rst
Mainly:
- Adjust indentation
- Add a TOC
- Define images where they are embedded
> [TASK] Revise GIFBUILDER examples chapter

- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Properties/Index.rst
- Documentation/Settings.cfg
- Improve description of "align"
- Add appropriate references
> [TASK] Revise GIFBUILDER object CROP

- Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
- Documentation/Settings.cfg
- Move example section to the top
> [TASK] Revise GIFBUILDER object ELLIPSE

- Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
- Documentation/Settings.cfg
> [TASK] Revise GIFBUILDER object EMBOSS

- Documentation/Gifbuilder/ObjectNames/Image/Index.rst
- Documentation/Settings.cfg
> [TASK] Revise GIFBUILDER object IMAGE

- Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
- Documentation/Settings.cfg
> [TASK] Revise GIFBUILDER object OUTLINE

- Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
- Documentation/Settings.cfg
> [TASK] Revise GIFBUILDER object SCALE

- Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
- Documentation/Settings.cfg
> [TASK] Revise GIFBUILDER object SHADOW

- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Gifbuilder/Properties.rst
> [TASK] Revise GIFBUILDER properties

- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Gifbuilder/Properties.rst
> [TASK] Revise GIFBUILDER properties (#888)

- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Gifbuilder/Properties.rst
> [Backport 11.5] [TASK] Revise GIFBUILDER properties (#888) (#892)

- Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
- Documentation/Settings.cfg
> [TASK] Revise GIFBUILDER object WORKAREA

- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Settings.cfg
- Remove hideButCreateMap property as this was removed in some TYPO3 version before v11.5
> [TASK] Revise GIFBUILDER object TEXT

- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
- Documentation/Gifbuilder/Properties.rst
- Documentation/Settings.cfg
> [TASK] Introduce custom types for GIFBUILDER properties

- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
- Documentation/Gifbuilder/Properties.rst
- Documentation/Settings.cfg
> [TASK] Introduce custom types for GIFBUILDER properties (#903)

- Documentation/Gifbuilder/Properties.rst
> [TASK] Adjust sorting of GIFBUILDER properties

- Documentation/Gifbuilder/Examples.rst
- Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
- Documentation/Gifbuilder/ObjectNames/Box/Index.rst
- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
- Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
- Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
- Documentation/Gifbuilder/ObjectNames/Image/Index.rst
- Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
- Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
- Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
- Documentation/Gifbuilder/Properties.rst
- Documentation/Settings.cfg
This eases the migration to the PHP-based documentation rendering.
> [TASK] Use confval instead of custom t3-gifbuilder-... directives

- Documentation/Functions/Stdwrap.rst
As it is referenced from the changelog
> [BUGFIX] Reintroduce label

- Documentation/AppendixA/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/747
Releases: main
> [TASK] #102605 - TSFE->fe_user removed

- Documentation/UsingSetting/AccessTypoScriptWithExtensions.rst
Additionally, add a caption to a code snippet and use text roles for TypoScript.
> [TASK] Add links to "Access TypoScript" chapter

- Documentation/Conditions/Index.rst
Additionally, fix some mix-ups with "Parameter" and "Type". Also, "Mixed" is used instead of "Custom" for data types.
> [TASK] Replace "aspect" with confval in "Conditions" chapter

- Documentation/ContentObjects/Index.rst
> [TASK] Replace "aspect" role in cObject chapter

- Documentation/ContentObjects/Index.rst
> [Backport 11.5] [TASK] Replace aspect role in cObject chapter (#931)

- Documentation/AppendixA/Index.rst
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82007
Releases: main
> [TASK] #102547 - Avoid TSFE->type

- Documentation/AppendixA/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/752
Releases: main
> [TASK] #102621 - TSFE members marked as read-only

- Documentation/AppendixA/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/770
Releases: main
> [TASK] #102715 - Add alternatives for TSFE properties

- Documentation/ContentObjects/Image/Index.rst
- Documentation/Settings.cfg
Additionally:
- Anchors added where missing
- Data types (like string, integer, boolean) are linked
> [TASK] Replace "t3-cobj-image" with "confval"

- Documentation/Functions/Typolink.rst
- Documentation/MenuObjects/Tmenuitem/Index.rst
This is a preparation for more adjustments in this chapter.
Mainly:
- Adjust indentation
- Link data types
- Link properties
> [TASK] Streamline TMENUITEM chapter

- Documentation/ContentObjects/Records/Index.rst
- Documentation/Settings.cfg
Additionally:
- Data type (boolean) is linked
> [TASK] Replace "t3-cobj-records" with "confval"

- Documentation/MenuObjects/Tmenuitem/Index.rst
- Documentation/Settings.cfg
Additionally:
- Data types (boolean, target) are linked
> [TASK] Replace "t3-menu-tmenu-item" with "confval"

- Documentation/ContentObjects/Extbaseplugin/Index.rst
https://typo3.slack.com/archives/C028JEPJL/p1706040485140539
> [BUGFIX] Better wording

- Documentation/ContentObjects/Svg/Index.rst
- Documentation/Settings.cfg
Additionally:
- Data types (integer, string) are linked
> [TASK] Replace "t3-cobj-svg" with "confval"

- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-cobj-user" with "confval"

- Documentation/Functions/Typolink.rst
- Documentation/Settings.cfg
- Documentation/Setup/Config/Index.rst
> [TASK] Replace "t3-tlo-config" with "confval"

- Documentation/TopLevelObjects/Plugin.rst
And use the same name as in the other examples
> Make example abbide to extbase naming scheme

- Documentation/Settings.cfg
- Documentation/Setup/Config/Index.rst
> [Backport 11.5] [TASK] Replace "t3-tlo-config" with "confval" (#1052)

- Documentation/Functions/Data.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/790
Related: #1064
Releases: main
> [TASK] Add missing versionchanged for applicationcontext

- Documentation/Functions/HtmlparserTags.rst
See: https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Html/HtmlParser.php#L512-L517
> [TASK] Resolve todos in HtmlparserTags chapter

- Documentation/Functions/If.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-if" with "confval"

- Documentation/Functions/Imagelinkwrap.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-imagelinkwrap" with "confval"

- Documentation/Functions/Makelinks.rst
- Documentation/Settings.cfg
Additionally:
- Adjust indentations
> [TASK] Replace "t3-function-makelinks" with "confval"

- Documentation/Functions/Parsefunc.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-parsefunc" with "confval"

- Documentation/Functions/Replacement.rst
- Documentation/Settings.cfg
Additionally:
- Link to PCRE manual
> [TASK] Replace "t3-function-replacement "confval" (#1094)

- Documentation/Functions/Round.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-round" with "confval"

- Documentation/Functions/Select.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-select" with "confval"

- Documentation/Functions/Tags.rst
- Documentation/Settings.cfg
Additionally:
- Adjust indentations
> [TASK] Replace "t3-function-tags" with "confval"

- Documentation/Functions/Parsefunc.rst
> [TASK] Enhance example about parseFunc.short (#1127)

- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/MenuObjects/Tmenuitem/Index.rst
> [TASK] Set unique names for confvals in TMENU chapter

- Documentation/Setup/Config/Index.rst
> [TASK] Set unique names for confvals in config chapter

- Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
- Documentation/Gifbuilder/ObjectNames/Box/Index.rst
- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
- Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
- Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
- Documentation/Gifbuilder/ObjectNames/Image/Index.rst
- Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
- Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
- Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
- Documentation/Gifbuilder/Properties.rst
> [TASK] Set unique names for confvals in Gifbuilder chapter

- Documentation/Functions/Cache.rst
- Documentation/Functions/Encapslines.rst
- Documentation/Functions/Htmlparser.rst
- Documentation/Functions/HtmlparserTags.rst
- Documentation/Functions/If.rst
- Documentation/Functions/Imagelinkwrap.rst
- Documentation/Functions/Imgresource.rst
- Documentation/Functions/Makelinks.rst
- Documentation/Functions/Numberformat.rst
- Documentation/Functions/Numrows.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Replacement.rst
- Documentation/Functions/Round.rst
- Documentation/Functions/Select.rst
- Documentation/Functions/Split.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Strpad.rst
- Documentation/Functions/Tags.rst
- Documentation/Functions/Typolink.rst
> [TASK] Set unique names for confvals in TypoScript functions chapter

- Documentation/DataTypes/Index.rst
> [TASK] Set unique names for confvals in datatypes chapter

- Documentation/Conditions/Index.rst
> [TASK] Set unique names for confvals in conditions chapter

- Documentation/Conditions/Index.rst
> [TASK][BACKPORT 11.5] Set unique names for confvals in cobjects chapter

- Documentation/DataTypes/Index.rst
> [BUGFIX] Fix references to confvals

- Documentation/Functions/Data.rst
* Use confvals instead of aspects
* Give headlines to examples
* Some small changes where content didnt make sense
> [TASK] Overhaul data / gettext chapter

- Documentation/Setup/Page/Index.rst
* Use confvals instead of tables
* Give headlines to examples
* Introduce a toc for the properties
> [TASK] Overhaul PAGE chapter

- Documentation/Functions/Index.rst
> [TASK] Overhaul functions overview pager

- Documentation/ContentObjects/Hmenu/Browse.rst
> [TASK] Overhaul HMENU browse page

- Documentation/ContentObjects/Hmenu/Directory.rst
> [TASK] Overhaul HMENU directory page

- Documentation/ContentObjects/Hmenu/Keywords.rst
> [TASK] Overhaul HMENU Keywords page

- Documentation/ContentObjects/Hmenu/Language.rst
> [TASK] Overhaul HMENU Language page

- Documentation/ContentObjects/Hmenu/Rootline.rst
> [TASK] Overhaul HMENU root line page

- Documentation/TopLevelObjects/Plugin.rst
> [TASK] Overhaul plugin page

- Documentation/ContentObjects/Hmenu/List.rst
> [TASK] Overhaul HMENU List page

- Documentation/AppendixA/Index.rst
> [TASK] Overhaul appendix page

- Documentation/TopLevelObjects/Other.rst
* Use confvals
* Improve descriptions
* Add examples
> [TASK] Overhaul other reserved toplevel objects page

- Documentation/Functions/Data.rst
Resolves: #1212
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/444
> [FEATURE] #100405 - Add data function "request"

- Documentation/Functions/Data.rst
- Documentation/Functions/Imagelinkwrap.rst
This increases the readability as the separate parts are better visible.
> [TASK] Streamline array usage examples in data function

- Documentation/ContentObjects/Index.rst
> [TASK] Use glob for content objects menu

- Documentation/ContentObjects/Fluidtemplate/DataProcessing.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/Fluidtemplate/_includes/_AfterMigrationToPageview.typoscript
- Documentation/ContentObjects/Fluidtemplate/_includes/_BeforeMigrationToPageview.typoscript
- Documentation/ContentObjects/Pageview/Index.rst
- Documentation/ContentObjects/Pageview/_includes/_DisplayPageInfo.html
- Documentation/ContentObjects/Pageview/_includes/_DisplaySiteTitle.html
- Documentation/ContentObjects/Pageview/_includes/_LinkToRootPage.html
- Documentation/ContentObjects/Pageview/_includes/_PageWithBreadcrumb.html
- Documentation/ContentObjects/Pageview/_includes/_PageWithConstant.html
- Documentation/ContentObjects/Pageview/_includes/_PageWithVariables.html
- Documentation/ContentObjects/Pageview/_includes/_PartialBreadCrumb.html
- Documentation/ContentObjects/Pageview/_includes/_PartialMainNavigation.html
- Documentation/ContentObjects/Pageview/_includes/_constants.typoscript
- Documentation/ContentObjects/Pageview/_includes/_pageWithBreadcrumb.typoscript
- Documentation/ContentObjects/Pageview/_includes/_pageWithFluid.typoscript
- Documentation/ContentObjects/Pageview/_includes/_pageWithVariables.typoscript
Releases: main
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage-Code/pull/17
Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/886
> [FEATURE] PAGEVIEW - Optimized integration of Page Rendering via Fluid

- .ddev/config.yaml
- Documentation/UsingSetting/AddTypoScriptWithExtensions.rst
- Documentation/UsingSetting/Entering.rst
- Documentation/UsingSetting/Index.rst
- Documentation/UsingSetting/SiteTypoScriptProvider.rst
- Documentation/UsingSetting/_Sets/_MyExtensionWithACoolFeature_config.yaml
- Documentation/UsingSetting/_Sets/_MyExtension_config.yaml
- Documentation/UsingSetting/_Sets/_MySitepackage_config.yaml
- Documentation/UsingSetting/_Sets/_TcaOverridesSystemplateV12.php
- Documentation/UsingSetting/_Sets/_ext_localconf.php
- Documentation/UsingSetting/_Sets/_mysite_config.yaml
Releases: main
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/890
> [FEATURE] Add TypoScript provider for sites and sets

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Minor language improvements
Releases:main, Backport 12.4)
> Overhaul Fluidtemplate

- Documentation/TopLevelObjects/Plugin.rst
* Use confval list
* link between examples and settings
* reorder that settings and examples are distinct lists, reuse examples where feasable
> [TASK] Refactor Plugin page

- Documentation/Setup/Config/Index.rst
* Use confval list
* link between examples and settings
* reorder that settings and examples are distinct lists, reuse examples where feasible
> [TASK] Refactor CONFIG page

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/Index.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
This prevents 403 Forbidden errors when switching to a version that did not exist in that version.
I will make a redirect
> [TASK] Move Dataprocessing.rst to Dataprocessing/Index.rst

- Documentation/TopLevelObjects/Plugin.rst
Add documentation for settings.persistence.classes.[classname].newRecordStoragePid
> [TASK] Add documentation for extbase newRecordStoragePid setting

- Documentation/DataTypes/Index.rst
- Documentation/DataTypes/_FunctionName.php
Move PHP example to file
Insert third parameter
references #1266
> [TASK] Follow up: add example PHP #1266

- Documentation/AppendixA/Index.rst
- Documentation/AppendixA/_MyExtensionControllerDI.php
- Documentation/AppendixA/_MyExtensionControllerExtbase.php
> [TASK] Move Appendix code examples to files

- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/ContentObjects/UserAndUserInt/_ExampleListRecords.php
- Documentation/ContentObjects/UserAndUserInt/_ExampleListRecords.typoscript
- Documentation/ContentObjects/UserAndUserInt/_ExampleTime.php
- Documentation/ContentObjects/UserAndUserInt/_ExampleTime.typoscript
- Documentation/ContentObjects/UserAndUserInt/_Hostname.php
- Documentation/ContentObjects/UserAndUserInt/_Hostname.typoscript
> [TASK] Move USER_INT code examples to files

- Documentation/Conditions/Index.rst
> [DOCS] Add condition example on using constants

- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/Fluidtemplate/_includes/_MyTemplate.html
- Documentation/ContentObjects/Fluidtemplate/_includes/_example.typoscript
- Documentation/ContentObjects/Fluidtemplate/_includes/_fluidtemplate-file.typoscript
- Documentation/ContentObjects/Fluidtemplate/_includes/_layoutRootPaths.typoscript
- Documentation/ContentObjects/Fluidtemplate/_includes/_settings.typoscript
- Documentation/ContentObjects/Fluidtemplate/_includes/_templateName.typoscript
- Documentation/ContentObjects/Fluidtemplate/_includes/_templateNameAutomatic.typoscript
- Documentation/ContentObjects/Fluidtemplate/_includes/_templateRootPaths.typoscript
Also correct indentation. No content changes
releases: 12.4, main
> [TASK] Move code snippets to separate includes

- Documentation/ContentObjects/Pageview/Index.rst
- Documentation/DataProcessing/Index.rst
- Documentation/DataProcessing/PageContentFetchingProcessor.rst
- Documentation/DataProcessing/_PageContentFetchingProcessor/_BackendLayout.tsconfig
- Documentation/DataProcessing/_PageContentFetchingProcessor/_BackendLayout.typoscript
- Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/922
RELEASES: main
> [FEATURE] Group-based content fetching in Frontend

- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/DataProcessing/DatabaseQueryProcessor.rst
- Documentation/DataProcessing/Index.rst
- Documentation/DataProcessing/RecordTransformationProcessor.rst
- Documentation/DataProcessing/_RecordTransformationProcessor/_FluidUsage.html
- Documentation/DataProcessing/_RecordTransformationProcessor/_WithDatabaseFluidTemplate.typoscript
- Documentation/DataProcessing/_RecordTransformationProcessor/_WithDatabaseQueryProcessor.typoscript
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/918
releases: main
> [FEATURE] Add record-based transformation Data Processor

- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/Pageview/Index.rst
see also https://github.com/TYPO3-Documentation/render-guides/issues/630
> [BUGFIX] Fix links to viewhlepers

- Documentation/TopLevelObjects/Module.rst
> Correct wording in Module.rst (#1297)

- Documentation/UsingSetting/AccessTypoScriptWithExtensions.rst
- Documentation/UsingSetting/AddTypoScriptWithExtensions.rst
- Documentation/UsingSetting/Constants.rst
- Documentation/UsingSetting/Debugging.rst
- Documentation/UsingSetting/Entering.rst
- Documentation/UsingSetting/Index.rst
- Documentation/UsingSetting/Register.rst
- Documentation/UsingSetting/SiteTypoScriptProvider.rst
- Documentation/UsingSetting/TheConstantEditor.rst
Before applying changes from  https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/136
> [TASK] Fix Whitespace in Using setting typoscript

- Documentation/Functions/Data.rst
- Documentation/Functions/If.rst
- if: https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/If.html
- Data getText: https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Data.html#data-gettext
> Mention `//` (double slash) operator

- Documentation/guides.xml
See also https://github.com/TYPO3-Documentation/render-guides/pull/745
> [TASK] Display confvals as TypoScript in Search facets

- Documentation/TopLevelObjects/Other.rst
> Add a contents menu for Reserved TLOs

- Documentation/Conditions/Index.rst
- Documentation/Functions/Data.rst
> [TASK] Remove version hints for 12.4 and use 13.4 as main example

- Documentation/DataProcessing/CommaSeparatedValueProcessor.rst
- Documentation/DataProcessing/DatabaseQueryProcessor.rst
- Documentation/DataProcessing/FilesProcessor.rst
- Documentation/DataProcessing/FlexFormProcessor.rst
- Documentation/DataProcessing/GalleryProcessor.rst
- Documentation/DataProcessing/LanguageMenuProcessor.rst
- Documentation/DataProcessing/MenuProcessor.rst
- Documentation/DataProcessing/PageContentFetchingProcessor.rst
- Documentation/DataProcessing/RecordTransformationProcessor.rst
- Documentation/DataProcessing/SiteLanguageProcessor.rst
- Documentation/DataProcessing/SiteProcessor.rst
- Documentation/DataProcessing/SplitProcessor.rst
> [TASK] Introduce confval menues for processor options

- .editorconfig
With additional Makefile setting
> [TASK] Use Core .editorconfig

- Documentation/ContentObjects/Fluidtemplate/Index.rst
> [TASK] Remove outdated warning from FLUIDTEMPLATE.template

- Documentation/Conditions/Index.rst
- Documentation/ContentObjects/Extbaseplugin/Index.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/Hmenu/Tmenu/Index.rst
- Documentation/DataProcessing/CommaSeparatedValueProcessor.rst
- Documentation/DataProcessing/DatabaseQueryProcessor.rst
- Documentation/DataProcessing/FilesProcessor.rst
- Documentation/DataProcessing/FlexFormProcessor.rst
- Documentation/DataProcessing/GalleryProcessor.rst
- Documentation/DataProcessing/LanguageMenuProcessor.rst
- Documentation/DataProcessing/MenuProcessor.rst
- Documentation/DataProcessing/SiteLanguageProcessor.rst
- Documentation/DataProcessing/SiteProcessor.rst
- Documentation/DataProcessing/SplitProcessor.rst
- Documentation/Functions/Data.rst
- Documentation/Functions/If.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Typolink.rst
- Documentation/TopLevelObjects/Config.rst
- Documentation/TopLevelObjects/Module.rst
- Documentation/TopLevelObjects/Page/Index.rst
- Documentation/TopLevelObjects/Plugin.rst
- Documentation/UsingSetting/Constants.rst
- Documentation/UsingSetting/Debugging.rst
- Documentation/UsingSetting/Entering.rst
- Documentation/UsingSetting/TheConstantEditor.rst
> [TASK] Remove TYPO3 v12.4 related version hints

- Documentation/About.rst
- Documentation/Index.rst
- Documentation/Introduction/Index.rst
> [BUGFIX] Fix links to the TypoScript Guide

- Documentation/DataProcessing/PageContentFetchingProcessor.rst
- Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1140
> [TASK] Improve `page-content` data processor description

- Documentation/Guide/CreateAMenu/Index.rst
- Documentation/Guide/NextSteps/Index.rst
- Documentation/Guide/ReadingContentRecords/ContentElements/Index.rst
- Documentation/Guide/ReadingContentRecords/Index.rst
- Documentation/Guide/TypoScriptFunctions/If/Index.rst
- Documentation/Guide/TypoScriptFunctions/ImgResource/Index.rst
- Documentation/Guide/TypoScriptFunctions/Index.rst
- Documentation/Guide/TypoScriptFunctions/Split/Index.rst
- Documentation/Guide/TypoScriptFunctions/Typolink/Index.rst
- Documentation/Guide/TypoScriptObjects/DatabaseQueries/Index.rst
- Documentation/Guide/TypoScriptObjects/FurtherObjects/Index.rst
- Documentation/Guide/TypoScriptObjects/RenderingContent/Index.rst
- Documentation/Guide/TypoScriptOverview/BackendConfiguration/Index.rst
- Documentation/Guide/TypoScriptOverview/FirstSteps/Index.rst
- Documentation/Guide/TypoScriptOverview/Index.rst
- Documentation/Guide/TypoScriptOverview/MainTemplate/Index.rst
- Documentation/Guide/TypoScriptOverview/Prerequisites/Index.rst
- Documentation/Guide/TypoScriptOverview/TheTermTemplate/Index.rst
- Documentation/Guide/TypoScriptOverview/TypoScriptAnArray/Index.rst
- Documentation/Guide/TypoScriptOverview/WhyTypoScript/Index.rst
- Documentation/Guide/UsingFluidStyledContent/Index.rst
- Documentation/Guide/UsingGetText/Index.rst
- Documentation/Guide/UsingStdWrap/CObject/Index.rst
- Documentation/Guide/UsingStdWrap/HeedTheOrder/Index.rst
- Documentation/Guide/UsingStdWrap/Index.rst
- Documentation/Guide/UsingStdWrap/ModifyTheOrder/Index.rst
> [TASK] Unify headlines

- Documentation/ContentObjects/Pageview/Index.rst
> Add information on how to access site settings

- Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock1.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock2.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock3.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidClosingBrace.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidCondition.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidImport.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Comments.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Conditions1.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Conditions2.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Conditions3.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Conditions4.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Conditions5.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Identifiers1.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/Identifiers2.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorAssignment.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy1.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy2.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy3.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy4.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorMultiLine.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorReference.rst.txt
- Documentation/CodeSnippets/TypoScriptSyntax/OperatorUnset.rst.txt
- Documentation/Index.rst
- Documentation/Syntax/CodeBlocks/Index.rst
- Documentation/Syntax/Comments/Index.rst
- Documentation/Syntax/Conditions/Index.rst
- Documentation/Syntax/FileImports/Index.rst
- Documentation/Syntax/Identifiers/Index.rst
- Documentation/Syntax/Index.rst
- Documentation/Syntax/Operators/Index.rst
> [TASK] Move the TypoScript Syntax chapter into the reference

- Documentation/About.rst
- Documentation/Conditions/Index.rst
- Documentation/Glossary.rst
- Documentation/Guide/Index.rst
- Documentation/Guide/NextSteps/Index.rst
- Documentation/Guide/TypoScriptOverview/_Chapters/_FirstSteps.rst.txt
- Documentation/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/Syntax/FileImports/Index.rst
- Documentation/TopLevelObjects/Index.rst
- Documentation/TopLevelObjects/Other.rst
- Documentation/UsingSetting/Constants.rst
- Documentation/UsingSetting/Entering.rst
> [TASK] Adjust TypoScript Syntax links

- Documentation/Guide/Content/_snippets/_FLUIDTEMPLATE.typoscript
- Documentation/Guide/FirstSteps/Index.rst
- Documentation/Guide/FirstSteps/_snippets/_mypage.php
- Documentation/Guide/FirstSteps/_snippets/_mypage.typoscript
- Documentation/Guide/FirstSteps/_snippets/_mypage2.typoscript
- Documentation/Guide/FirstSteps/_snippets/_mypage3.typoscript
- Documentation/Guide/FirstSteps/_snippets/_mypage4.typoscript
- Documentation/Guide/FirstSteps/_snippets/_mypage5.typoscript
- Documentation/Guide/Index.rst
- Documentation/Guide/Overview/_Chapters/_TheTermTemplate.rst.txt
- Documentation/Guide/Page/Index.rst
- Documentation/Guide/Page/_Default.html
- Documentation/Guide/Page/_css-loading.typoscript
- Documentation/Guide/Page/_favicon.typoscript
- Documentation/Guide/Page/_fluid-template.typoscript
- Documentation/Guide/Page/_hello-world.typoscript
- Documentation/Guide/Page/_javascript-loading.typoscript
- Documentation/Guide/Page/_tracking-code.typoscript
- Documentation/TopLevelObjects/Page/Index.rst
> [FEATURE] Add chapter about PAGE to the TS guide

- Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
> [BUGFIX] jumbotrong -> jumbotron

- Documentation/ContentObjects/Pageview/_includes/_LinkToRootPage.html
> [BUGFIX] In PAGEVIEW rootpage is found in site not page

- Documentation/DataProcessing/PageContentFetchingProcessor.rst
- Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/pull/239
> [TASK] cObject retrieves raw record automatically

- Documentation/DataProcessing/RecordTransformationProcessor.rst
Resovles: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1028
> [TASK] Extend RecordInterface

- Documentation/TopLevelObjects/Config.rst
> Prevent citation box

- Documentation/DataProcessing/PageContentFetchingProcessor.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1165
> [FEATURE] Allow modifying fetched page content

- Documentation/Functions/If.rst
Resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/1488
> [BUGFIX] Fix "if" examples

- Documentation/Functions/Stdwrap.rst
> [TASK] Clean up and order stdwrap

- Documentation/PageTsconfig/TceMain.rst
> Fix indentation of example

- Documentation/DataProcessing/SiteProcessor.rst
> fix: correct typo on site data processor page

- Documentation/Syntax/Index.rst
- Documentation/Syntax/TSconfig/Index.rst
- Documentation/UsingSettingTSconfig/Index.rst
> [TASK] Move TSconfig Syntax into general syntax chapter

- Documentation/UsingSettingTSconfig/Index.rst
> [TASK] Use new Cards directive

- Documentation/TopLevelObjects/Page/Index.rst
> fix: avoid new line in the middle of a sentence

- Documentation/PageTsconfig/Mod/WebList.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/850
> [BUGFIX] Handle record export and download options individually

- Documentation/DataProcessing/MenuProcessor/Browse.rst
References: https://review.typo3.org/c/Packages/TYPO3.CMS/+/88332
> [BUGFIX] Provide default configuration for browse menu

- Documentation/PageTsconfig/Mod/WebLayout/_Default.html
The old code did not work and caused errors. Changed cObject as described in [Site Package Tutorial](https://docs.typo3.org/permalink/t3sitepackage:cm-fluid-typoscript-mapping).
> Corrected <f:cObject> in  _Default.html

- Documentation/Guide/Page/_fluid-template.typoscript
Assign "PAGE" instead of "10" here.
> Fix wrong assignment

- Documentation/ContentObjects/UserAndUserInt/_Hostname.php
> Add ServerRequestInterface to user function

- Documentation/Syntax/Operators/Index.rst
> Update titles and add toc

- Documentation/UserTsconfig/Auth.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1272
Releases: main
> [TASK] Deprecate User TSConfig option auth.BE.redirectToURL

- Documentation/Conditions/Index.rst
- Documentation/PageTsconfig/Rte.rst
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1281
Releases: main
> [FEATURE] Introduce expression for accessing site locale
