- Documentation/ContentObjects/UserAndUserInt/Index.rst
The option was removed in 2012 with commit
fb0b7724ed692ac458f97426f80bb2553d52c269 in TYPO3.CMS repository.
Change-Id: I6fce23b4bf379cc78e8d5e9ece79cfee99130897
Releases: master, 6.2
> [CLEANUP] Remove obsolete note on allowed class prefixes

- Documentation/ContentObjects/Fluidtemplate/Index.rst
partialRootPaths and layoutRootPaths do not have stdWrap support
> [BUGFIX] Removed wrong stdWrap from *RootPaths

- Documentation/Setup/Config/Index.rst
config.debug does not only affect menu content objects but also parsetime output.
> [TASK] Mention parsetime output for config.debug

- Documentation/MenuObjects/Gmenu/Index.rst
Remove documentation of non-existent property "wrapItemAndSub" in GMENU. Corrected documentation according to this change: https://review.typo3.org/#/c/36806/1
> Remove documentation of non-existent property "wrapItemAndSub" in GMENU

- Documentation/Setup/Page/Index.rst
Mention the TypoScript config moveJsFromHeaderToFooter in page.includeJS to avoid confusion why JS files are rendered into the footer.
> Mention config.moveJsFromHeaderToFooter in includeJS

- Documentation/Conditions/Reference/Index.rst
fixed a small error in Conditions-Reference for "dayofyear" example. If the first day of the year (January, 1st) is 0 than [dayofyear = 5] will be true on January 6th, not [dayofyear = 7]
> fix example for Condition "dayofyear"

- Documentation/Functions/Cache/Index.rst
The caching framework is always enabled now.
> Remove information about caching framework

- Documentation/Gifbuilder/ObjectNames/Index.rst
The „edge“ transform offered by ImageMagick and GraphicsMagick performs edge detection on the image, not rounded corners.
Resolves: #26065
> [BUGFIX] Properly document GIFBUILDER edge effect

- Documentation/ContentObjects/UserAndUserInt/Index.rst
The global `includeLibs` functionality has been removed. Thus, we need to adapt the examples accordingly
> [BUGFIX] Fix example for library inclusion

- Documentation/Functions/Filelink/Index.rst
- Documentation/Functions/Typolink/Index.rst
- Documentation/Includes.txt
- Documentation/Setup/Config/Index.rst
The documentation is moved to the jumpurl sysext.
See:
https://forge.typo3.org/issues/52156
https://review.typo3.org/#/c/36211/
> [TASK] Remove jumpurl documentation

- Documentation/Functions/Stdwrap/Index.rst
We no longer allow includeLibs.
Furthermore the example has been adapted to utilize namespaces.
> [BUGFIX] Align userFunc example with current code

- Documentation/DataTypes/Align/Index.rst
It's not needed any more. Style should not be part of HTML.
> Declare align deprecated with IMGTEXT and CTABLE

- Documentation/ContentObjects/Fluidtemplate/Index.rst
* Fix indentation (spaces instead of tabs) to reduce spaceusage on
rendered html.
* Streamline extension key examples.
* Use brackets to reduce amount of written code  So you don't have to
read so much and can follow the structure.
> [CLEANUP] cObject FLUIDTEMPLATE

- Documentation/Setup/Config/Index.rst
* As it can be a bit irritating at first, just added a small hint that
the actual configured ids have to be the ones of the pages of type
mount point, not of the targets.
* Added reference to setting via link.
* Added styling to php method and keyword.
* Also added a missing dot at the end of a sentence.
* Also fixed indentation done with tabs instead of spaces
> [FEATURE] Provide hint about usage for mount points

- Documentation/ContentObjects/Content/Index.rst
I think it useful to indicate the influence of the select query to hide some records automatically. It's basic information of the overall usefulness of this content element.
> Automatic visibility control of records

- Documentation/Functions/Stdwrap/Index.rst
insertData is dangerous if applied to e.g. content editing. This is not obvious without higher TYPO3 knowledge.
> Add warning to insertData

- Documentation/Setup/Config/Index.rst
for better understanding of config.pageRendererTemplateFile I add its default value;
related issue: https://forge.typo3.org/issues/60723
> [Task] add default for pageRendererTemplateFile

- Documentation/Setup/Config/Index.rst
the Property name is shown as 
Property
defaultGetVars
but the code example has it in weird mixed lowercase/uppercase mix
> fix 1 one-letterTypo

- Documentation/Functions/Typolink/Index.rst
- Documentation/Setup/Page/Index.rst
Documented: 
* https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.3/Feature-74365-LinkServiceForUnifiedReferencingSyntax.html
* https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.3/Breaking-77180-DroppedExtJSSupportInFrontendTypoScript.html
> [TASK] Updated docs for TYPO3 8.3

- Documentation/Setup/Config/Index.rst
Unified the layout,
making use of table layout for single properties, which were shown with simple layout (headlines)
> Unified the layout

- Documentation/DataTypes/Gettext/Index.rst
With https://forge.typo3.org/issues/17309 the new gettext
option 'flexform' has been added. It allows for the access
of flexform properties using TypoScript.
> [TASK] Add gettext field flexform

- Documentation/ContentObjects/UserAndUserInt/Index.rst
Remove backslash in USER\_INT and display some PHP code blocks as PHP code
> FIX: render USER_INT correctly

- Documentation/ContentObjects/Template/Index.rst
Imho "page.10 = TEMPLATE" should be mentioned since this part is about the TEMPLATE-object.
> Add missing line

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Hello,
shouldn't it read '.templateName' instead of '.template' ?
> Wrong Propertyname

- Documentation/ContentObjects/Form/Index.rst
Add a link to the form framework documentation draft as
the current link references the old form extension that does not
exist anymore in TYPO3 8 LTS
> Link the Form Framework documentation

- Documentation/Setup/Page/Index.rst
Add another example to cssInline and remove a line break which is not correct typoscript syntax
> Add another example to cssInline

- Documentation/Setup/Config/Index.rst
As mentioned in the `TypoScriptFrontendController.php` (line 2522) the default value would be `external` instead of `1`
```
// Set default values for removeDefaultJS and inlineStyle2TempFile so CSS and JS are externalized if compatversion is higher than 4.0
if (!isset($this->config['config']['removeDefaultJS'])) {
$this->config['config']['removeDefaultJS'] = 'external';
}
```
> Change default value of removeDefaultJs

- Documentation/Setup/Config/Index.rst
Make description of the sys_language_uid, sys_language_overlay and sys_language_mode more verbose and precise.
See typo3/sysext/frontend/Tests/Functional/Rendering/LocalizedContentRenderingTest.php
for a test covering different configuration combinations.
> Update description of the language related settings

- Documentation/ContentObjects/Image/Index.rst
A description has been given instead of showing the type of it.
> IMAGE params should be shown as string

- Documentation/ContentObjects/Fluidtemplate/Index.rst
In the example using "variables.foo = bar" seems irritating to me. The user expects to be able to call "foo" in the template then via {foo}. But that does not work because you have to use a CObject.
> Update Index.rst, make working example for "variables" property of FLUIDTEMPLATE

- Documentation/ContentObjects/Fluidtemplate/Index.rst
@marble is there anything more we could add about the FLUIDTEMPLATE format property?
where is it used? what can we do with it?
I just copied the text found at 
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/Mvc/Request.php#L465
From the path resolution in 
https://github.com/TYPO3/Fluid/blob/master/src/View/TemplatePaths.php#L253
it looks like this is the file suffix for the template file that will be used.
> add information about format

- Documentation/MenuObjects/Tmenu/Index.rst
"default" values block is rendered in the wrong position.
> change position of default block

- Documentation/ContentObjects/Content/Index.rst
Modified layout for properties to make them consistent with the other parts of documentation; please review and check the title formatting (I am not sure that they are correct)
> Use "Table" layout for properties

- Documentation/Setup/Config/Index.rst
It does not make sense to use config.tx_myextension_variable1, config.tx_myextension_variable2, config.tx_myextension_variable3
It is better to have an array.
> Allow config.tx_myextension.variable = value

- Documentation/Functions/Round/Index.rst
As of TYPO3 8.7 you need to enable rounding with round = 1
https://forge.typo3.org/issues/83859
> Add missing value and description

- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/Functions/Stdwrap/Index.rst
- Documentation/Setup/Config/Index.rst
- Documentation/Setup/Index.rst
- Documentation/Setup/Page/Index.rst
- Documentation/Setup/Plugin/Index.rst
- Documentation/Setup/Top-levelObjects/Index.rst
* Fix non existing cross references, mainly for data types.
* Fix missing roles for typoscript, html, etc.
* Fix missing syntax information for code highlighting, mainly php.
* Partly remove references to TYPO3 API, instead use PHP Role.
* Add `GLOBALS` to TYPO3_CONF_VARS to make it easy for copy and paste
and to make sure everyone is able to get that it's a global PHP array.
* Partly fix some PSR-2 in code examples, e.g. remove tabs, indent
curly braces.
* Partly remove inline line numbering for code examples, instead use
:linenos: option from sphinx.
* Partly add missing anchors to enable cross linking.
> TASK: Fix small issues

- Documentation/Functions/Stdwrap/Index.rst
With the Task #54091 strlen compares to zero are replaced by a check against '' (empty string).
> [TASK] Remove the mention of not longer used strlen function

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Make example work. Filtering intergers in processor, but outputting keywords in template contradicts itself.
> Optimize example for DataProcessing\SplitProcessor

- Documentation/ContentObjects/Image/Index.rst
There's a mistake in the `<picture>` element related sections. The `<source>` tags inside `<picture>` need to have a `srcset="..."` image set instead of `src="..."`. Otherwise the picture layout will not work.
See https://www.w3schools.com/tags/tag_source.asp for more details.
> Correct the <picture> descriptions

- Documentation/Conditions/Reference.rst
- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/Functions/If/Index.rst
- Documentation/Functions/Typolink/Index.rst
- Documentation/Setup/Config/Index.rst
See typo3/sysext/core/Documentation/Changelog/9.4/Feature-86057-ImprovedTypolinkURLLinkGeneration.rst
Remove mentions of the famous "L" parameter, as it is now superflous.
> [TASK] Introduce typolink.language

- Documentation/MenuObjects/Tmenu/Index.rst
These wraps are around all subitems and not around the item of TMENU.
> wrap around sub items

- Documentation/Setup/Page/Index.rst
The icon used for page.shortcutIcon is no longer required to be a .ico file
This commit remove the *note* part that mentions that
> A .ico file is no longer required for page.shortcutIcon

- Documentation/Conditions/Reference/Index.rst
As commented in AbstractConditionMatcher.php (and seen on line 676 in the same rst) the operator has to be `>=` instead of `=>`
> Fix typoscript condition

- Documentation/Conditions/Reference.rst
Register additional expressionLanguage providers has changed in sep 2018 with issue#86196. See https://review.typo3.org/#/c/58232/33/typo3/sysext/core/Classes/ExpressionLanguage/TypoScriptConditionProvider.php
Compare the documentation to this change. See
https://review.typo3.org/#/c/58232/33/typo3/sysext/core/Documentation/Changelog/9.4/Feature-85829-ImplementSymfonyExpressionLanguageForTypoScriptConditions.rst
> Update outdated code snippet for ExpressionLanguage

- Documentation/Setup/Config/Index.rst
Fix order and association of headlines to examples in "pageTitleSeparator" section.
> Fix order and association of headlines to examples

- Documentation/Setup/Config/Index.rst
The feature to use stdWrap for config.additionalHeaders has been removed due to an incompatibility with page caching.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Breaking-86492-RemovedStdWrapSupportForConfigadditionalHeaders.html
> [BUGFIX] Remove stdWrap support description and example for config.additionalHeaders

- Documentation/Conditions/Index.rst
pid is the parent id, example its not wrong, but confusing
> this takes id of page from database: uid

- Documentation/Functions/Typolink.rst
Currently pending https://review.typo3.org/q/I9a1f47f2eaaacc4368a1ca3e1a4006a8248e654e in order to get `file->identifier` aspect correct in TYPO3 core.
> [TASK] Add missing t3:// link handlers

- Documentation/Functions/Stdwrap.rst
The PHPDoc of `stdWrap_encodeForJavaScriptValue` in `TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer` is misleading, see https://forge.typo3.org/issues/88900 for related issue.
Resolves: #188
> TASK: Fix example of "encodeForJavaScriptValue"

- Documentation/DataTypes/Properties/GetText.rst.txt
site and siteLanguage is sub property of get text and should therefore
be on same level as all other sub properties.
Releases: 9.5, master
> [BUGFIX] Header level

- Documentation/ContentObjects/Fluidtemplate/Index.rst
With [feature 87748](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Feature-87748-AddSiteProcessor.html) the SiteProcessor as DataProcessor was introduced. The patch adds it to the documentation.
> Add SiteProcessor

- Documentation/Setup/Config/Index.rst
According to [feature 85678](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Feature-85678-AddAPIForTitleTags.html) and [PageTitle API](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/PageTitleApi/Index.html).
In v10 the altPageTitleProvider was removed already (different to PR #232).
See also: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html?highlight=altpagetitleprovider
> Add config.pageTitleProviders for TYPO3 v10

- Documentation/UsingSetting/TheConstantEditor.rst
- Adjust the subcategories according to https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/install/Classes/Service/ExtensionConfigurationService.php (which seems to be the same subcategories as for the constant editor)
- Refer to fluid_styled_content instead of css_styled_content
- Add link to static template for examples
> Adjust subcategories for content elements

- Documentation/Setup/Config/Index.rst
due to different underlining config.ftu was shown as a subheading from config.form mailCharset
> set config.ftu to normal level

- Documentation/MenuObjects/CommonProperties/Index.rst
To be compatible with descriptions from /ContentObjects/Hmenu/Index.rst
Add deprecation warnings see
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85902-IMGMENUGMENU.html
> Update Menu object common properties

- Documentation/Setup/Page/Index.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88772-JavaScriptScriptTagsOmitTypetextjavascriptInHTML5.html
> JavaScript script tags omit type=text/javascript in HTML5

- Documentation/Functions/Imagelinkwrap.rst
`imageLinkWrap.alternativeTempPath` has been removed before TYPO3 v6.2 already, see https://forge.typo3.org/issues/89618
> [DOCS] Remove imageLinkWrap.alternativeTempPath

- Documentation/Setup/Config/Index.rst
The examples are not rendered inside the container 't3-row'
because of an unnecessary blank line.
Releases: master
> Improve rendering of code example for 'PageTitleProviders'

- Documentation/Setup/Config/Index.rst
In the examples for 'config.cache', the explanation (with colon)
came after the related code block. The reversed order is more logical.
Releases: master, 9.5, 8.7, 7.6
> Improve order of examples

- Documentation/Index.rst
- remove Previous Key:	doc_core_tsref
- remove email DocTeam from startpage, add link
to feedback section
- remove Rendered Date (is in footer)
> Remove outdated or redundant info from startpage

- Documentation/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/Settings.cfg
The term "Typoscript" is currently used for the TypoScript syntax
and for TypoScript templating.
We now use "TypoScript Template" when referring to TypoScript templates
to avoid confusion
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/77
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/120
> Change title to "TypoScript Template Reference"

- Documentation/ContentObjects/Hmenu/Index.rst
The list of `excludeDoktypes` still included the long-time removed value "5"  -see also https://forge.typo3.org/issues/90472
Please review and backport at will. Thank you.
> Update list of excludeDoktypes

- Documentation/Setup/Page/Index.rst
extJS is no longer part of TYPO3. Change the misleading description text for inlineSettings.
> Change misleading description for inlineSettings

- Documentation/Setup/Page/Index.rst
The "same as includeJSLibs" pointed to itself. "Above" was not always pointing to something above but rather below.
> Fix references to paragraphs on same page

- Documentation/Functions/Stdwrap.rst
This is no longer supported by feedit.
Even if extensions exist which support this option, it should not be promoted anymore.
Instead people should use Css files.
> Remove styleAttribute attribute for editIcons

- Documentation/Setup/Config/Index.rst
This key was removed with https://forge.typo3.org/issues/87980.
> Remove message_page_is_being_generated

- Documentation/Setup/Page/Index.rst
In `typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php` `cObjGet()` filters and sorts the array keys with `filterAndSortByNumericKeys()` and the help of `MathUtility::canBeInterpretedAsInteger()`.
This is done by a type cast to `int` and a comparison with the original key. This type cast fails with numbers greater than `2147483647` on 32bit operation systems. Yes, there are still web hosting companies out there with 32bit operation systems!
> Add hint for 32bit operating systems

- Documentation/Setup/Config/Index.rst
The following TypoScript options have been removed in TYPO3 v10.0:
- config.concatenateJsAndCss
- config.defaultGetVars
- config.htmlTag_langKey
- config.htmlTag_dir
- config.language
- config.language_alt
- config.locale_all
- config.sys_language_isocode
- config.sys_language_isocode_default
- config.sys_language_mode
- config.sys_language_overlay
- config.sys_language_uid
- config.titleTagFunction
- config.tx_extbase.objects
- config.typolinkCheckRootline
- config.typolinkEnableLinksAcrossDomains
- config.USERNAME_substToken
- config.USERUID_substToken
See also: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html
Related: #288
Releases: master, 10.4
> [TASK] Remove dropped TypoScript config options

- Documentation/AppendixA/Index.rst
/**
* Renders a content object
*
* @param string $name The content object name, eg. "TEXT" or "USER" or "IMAGE
* @param array $conf The array with TypoScript properties for the content object
* @param string $TSkey A string label used for the internal debugging tracking.
* @return string cObject output
* @throws \UnexpectedValueException
*/
public function cObjGetSingle($name, $conf, $TSkey = '__')
{
> cObjGetSingle can have a third parameter

- Documentation/ContentObjects/Fluidtemplate/Index.rst
There is no such thing as colPos in .select, see https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Select.html for Reference
> Corrcted Example, colPos is not in .select

- Documentation/Conditions/Index.rst
Due to https://review.typo3.org/c/Packages/TYPO3.CMS/+/63752 the statement `available in BE only` is not true anymore
> Remove out of date information about the scope of the `backend` symfony expression

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Before, there was no overview of what properties are on the page.
With this change you can now jump directly to a property by clicking
on a link of the list on top of page. Also, you get a better overview
of which properties exit.
- add table of content for content on page (level 1)
- add list of properties
- order properties alphabetically
Related: #323
> Add table of contents and list of properties to FLUIDTEMPLATE

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Before, there was no overview of what properties are on the page.
With this change you can now jump directly to a property by clicking
on a link of the list on top of page. Also, you get a better overview
of which properties exit.
- add table of content for content on page (level 1)
- add list of properties
- order properties alphabetically
Related: #323
This is a backport of #324
> Add table of contents and list of properties to FLUIDTEMPLATE (10.4)

- Documentation/ContentObjects/Fluidtemplate/Index.rst
Before, there was no overview of what properties are on the page.
With this change you can now jump directly to a property by clicking
on a link of the list on top of page. Also, you get a better overview
of which properties exit.
- add table of content for content on page (level 1)
- add list of properties
- order properties alphabetically
Related: #323
This is a backport of #324
> Add table of contents and list of properties to FLUIDTEMPLATE (9.5)

- Documentation/Functions/Split.rst
The line numbers in the example were not correct
> Fix wrong line numbers in Split.rst

- Documentation/Conditions/Index.rst
- feature flag TypoScript.strictSyntax is no longer available, change
text for this
- add information that new conditions are mandatory and add links to
changelogs
- add short overview of old / new conditions
- refer to deprecation log
> New condition syntax is now mandatory for 10 (10.4)

- Documentation/ContentObjects/Fluidtemplate/DataProcessing.rst
- there are 8 dataProcessors is no longer correct. Just use "several"
instead to avoid having to constantly update that.
- fix alphabetical ordering
- remove duplicate text
> Fix several error in dataProcessing

- Documentation/ContentObjects/Hmenu/Index.rst
Making it more clear which checkbox is meant by providing the exact name from the backend.
> Rephrase description of 'includeNotInMenu'

- Documentation/Conditions/Index.rst
- It can be changed in "Settings > Feature Toggles" and not "Settings > Configure Installation-Wide Options"
- Link to section on Feature Toggles in core
- refer to add alternative configuration file AdditionalConfiguration.php
https://docs.typo3.org/m/typo3/reference-typoscript/9.5/en-us/Conditions/Index.html#upgrading
> Fix section about changing Feature Toggle for conditions (9.5)

- Documentation/Functions/Typolink.rst
This one drove me crazy. :) The property is named `target` but it is ought to be `extTarget`
> Bugfix: name extTarget correctly

- Documentation/AppendixA/Index.rst
see Deprecation 88746
see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/849
> [TASK] Correct PageRepository reference

- Documentation/AppendixA/Index.rst
see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/850
and https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85389-VariousPublicPropertiesInFavorOfContextAPI.html
> [TASK] Remove properties, point to context api

- Documentation/Setup/Config/Index.rst
"Advanced" page type has been removed over 12 years ago (https://forge.typo3.org/issues/18108)
> Delete obsolete reference to "Advanced" page type

- Documentation/ContentObjects/Image/Index.rst
See Core Deprecation 90861
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/841
> [TASK] Remove old reference to cImage

- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/Functions/Typolink.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93041-RemoveTypoScriptOptionAddQueryStringmethod.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
> [TASK] Remove addQueryString.method

- Documentation/UsingSetting/AddTypoScriptWithExtensions.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
> [TASK] Remove TYPO3_REQUESTTYPE and TYPO3_mode

- Documentation/Conditions/Index.rst
Request does not work in CLI context, so it shouldn't be listed under "available in all contexts". I didn't test whether the other functions listed there work in CLI context but at least we have one improvement.
Also see https://forge.typo3.org/issues/91654
> Do not list "request" function as working in all contexts

- Documentation/Functions/Typolink.rst
Breaking: 88755 - Remove POST option from typolink.addQueryString.method (10.0)
merge into 10.4 only, there is another PR for master
resolves #341
> Breaking: 88755 - Remove POST option from typolink.addQueryString

- Documentation/Conditions/Index.rst
Only one member variable of $TSFE is listed.
Where should the other parts of $TSFE be described?
---------
/**
* The page id (int)
* @var string
*/
public $id = '';
/**
* The type (read-only)
* @var int|string
*/
public $type = '';
/**
/**
* Page will not be cached. Write only TRUE. Never clear value (some other
* code might have reasons to set it TRUE).
* @var bool
*/
public $no_cache = false;
/**
* The rootLine (all the way to tree root, not only the current site!)
* @var array
*/
public $rootLine = [];
/**
* The pagerecord
* @var array
*/
public $page = [];
/**
* This will normally point to the same value as id, but can be changed to
* point to another page from which content will then be displayed instead.
* @var int
*/
public $contentPid = 0;
> add example with page id

- Documentation/Functions/Select.rst
@see https://forge.typo3.org/issues/87551#note-2
@see:
https://github.com/TYPO3-CMS/frontend/blob/2afb96c6725d7751bdb2ca3a53e9566b2eaff52b/Classes/ContentObject/ContentObjectRenderer.php#L6053-L6056
https://github.com/TYPO3-CMS/frontend/blob/2afb96c6725d7751bdb2ca3a53e9566b2eaff52b/Classes/ContentObject/ContentObjectRenderer.php#L6078-L6081
> TypoScript select object: requirements for property pidInList = 0

- Documentation/Conditions/Index.rst
Releases: master, 10.4, 9.5
Source: https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/core/Classes/ExpressionLanguage/FunctionsProvider/DefaultFunctionsProvider.php#L128
> Mention traverse() result on missing array entry

- Documentation/MenuObjects/Tmenuitem/Index.rst
Add description to .after and .afterWrap properties (that seemed absent in documentation since 4.5?)  in order to solve https://forge.typo3.org/issues/91965
Please review it! I am not sure if I put them in the correct place that respects the TypoScript execution order!
Please backport it if you want
> add .after and .afterWrap properties

- Documentation/Setup/Config/Index.rst
Some language settings have been deprecated in TYPO3 but no deprecated notes added.
> [TASK] Add some hints for deprecated language settings (9.5)

- Documentation/Functions/Typolink.rst
Instead of a uid one can specify "current" to link to the current page.
> Mention the "current" page for typolink

- Documentation/Conditions/Index.rst
The documentation was recommending `site("configuration")["myCustomProperty"]` to access  configuration properties in TypoScript conditions. However, if the property has not been set, this will trigger a runtime exception, and your log will fill up quickly. Using `traverse()` will silence the error messages: `traverse(site("configuration"), "myCustomProperty")`.
Releases: master, 10.4
> [TASK] Recommend using traverse() to avoid errors

- Documentation/ContentObjects/Content/Index.rst
For better understanding of the CONTENT select
(Yes i know there are more but colpos, pid and orderby is used so many times together that it might help)
Releases: master, 10.4
> Added ColPos to increase understanding

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
See the link "select" in the "Note" box:
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.html#confval-dataProcessing
> Fix link in DatabaseQueryProcessor

- Documentation/Functions/Select.rst
When I worked with this property, I always got the line 
```sql
(`<table_name>`.`uid`= 0)
``` 
inserted into my query and it took me a long time to figure out, where this statement was from.
When you specify a bad doktype page id, which does not meet the criteria for [this method](https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L6765), the line is inserted.
Please add more notes like these.
> Add note for pidInList validation

- Documentation/ContentObjects/Hmenu/Index.rst
The doktype 5 does not exist anymore. With TYPO3 v10
the folder was added to the default excludeDoktypes
configuration.
See also: https://github.com/TYPO3/typo3/blob/master/typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php#L66
> [TASK] Adjust default HMENU excludeDoktypes configuration

- Documentation/Setup/Page/Index.rst
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95349-TypoScriptPageincludeCSSincludeCSSLibsimport.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1522
> [Deprecation] #95349 - TypoScript: page.includeCSS/includeCSSLibs.import

- Documentation/MenuObjects/CommonProperties/Index.rst
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95351-CustomJSWindowOptionsInHMENUSettings.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1522
> [Deprecation] #95351 - Custom JSWindow options in HMENU settings

- Documentation/Setup/Config/Index.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96616-RemoveFrontendLoginModeForPages.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
releases: main
> Breaking: #96616 - Remove Frontend Login Mode for pages

- Documentation/Setup/Config/Index.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96522-ConfigdisablePageExternalUrlRemoved.html
refs: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
releases: main
> Breaking: #96522 - config.disablePageExternalUrl removed

- Documentation/Functions/HtmlparserTags.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96501-PrefixLocalAnchorsOptionInHTMLParserRemoved.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
releases: main
> Breaking: #96501 - prefixLocalAnchors option in HTMLParser removed

- Documentation/MenuObjects/Tmenu/Index.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96708-RemovedSupportForAccesskeysInHMENU.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
> Breaking: #96708 - Removed support for accesskeys in HMENU

- Documentation/Setup/Page/Index.rst
In accordance with the core code base, "libs" in "includeJSFooterlibs" must be lowercase.
> Fixed spelling of "includeJSFooterlibs"

- Documentation/Setup/Config/Index.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97065-TYPO3FrontendAlwaysRenderedInUTF-8.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
> [BREAKING] TYPO3 Frontend always rendered in UTF-8

- Documentation/DataTypes/Properties/GetText.rst
In the example, "Here you are!" should be a subpage of "Site root"
- otherwise the description would be incorrect.
> Indent code snippet correctly

- Documentation/Setup/Config/Index.rst
solves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/80
> Breaking: #97550 - TypoScript option config.disableCharsetHeader removed

- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/Functions/Stdwrap.rst
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Deprecation-94956-PublicCObj.html
Additional changes:
- Adjust the extension name and namespace of the examples to be
in sync with the caption of the code blocks
- Add some syntax highlighting where appropriate
- Declare classes as final as best practise
> [TASK] #94956 - Use setContentObjectRenderer instead of public $cobj

- Documentation/Setup/Config/Index.rst
As there was no deprecation I will create another ticket for the 11.5 branch with an attention tag about the removal
Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/128
> Breaking: #97927 - Removed TypoScript option config.doctypeSwitch

- Documentation/ContentObjects/Svg/Index.rst
Adobe Flash does not exist anymore. Thus, no we don’t support Flash.
https://www.adobe.com/products/flashplayer/end-of-life.html
Lolli: flash svg fallback has been removed from core codebase in 2015 with https://review.typo3.org/c/Packages/TYPO3.CMS/+/38089/
> Remove Flash fallback hint

- Documentation/ContentObjects/Case/Index.rst
- Documentation/ContentObjects/CoaAndCoaInt/Index.rst
- Documentation/ContentObjects/Content/Index.rst
- Documentation/ContentObjects/Files/Index.rst
- Use Headlines
- Content Menü
- Sections for Properties and Examples
> Unify layout of all ContentObjects Part 1

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
The DatabaseQueryProcessor currently has issues with language/ version overlays, that cannot be easily resolved (complexity: nightmare). Thus, bugs like https://forge.typo3.org/issues/85284 or https://forge.typo3.org/issues/88071 occur.
See https://forge.typo3.org/issues/85284#note-5 for a more detailed explanation.
> Add warning for using the DatabaseQueryProcessor

- Documentation/Conditions/Index.rst
Cherry-pick from [4a87cc128d679ff7e22e99059e0e59f27ff32497](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/commit/4a87cc128d679ff7e22e99059e0e59f27ff32497)
> Add missing opening brace in code example

- Documentation/Conditions/Index.rst
- Documentation/ContentObjects/Content/Index.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/Functions/Select.rst
Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#295
Additionally, link to current LTS version of Symfony expression language.
> [TASK] Correct spelling of TYPO3 versions

- Documentation/Conditions/Index.rst
- Documentation/ContentObjects/Content/Index.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/Functions/Select.rst
Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#295
Additionally, link to current LTS version of Symfony expression language.
> [TASK] Correct spelling of TYPO3 versions (#575)

- Documentation/Functions/Data.rst
- Documentation/Functions/Index.rst
It is way to complex to be considered a datatype. 
Also it was invisible in the menu as it was made an orphan accidently.
Sort the functions by alphabet and display them as glob
> Move data/gettext in with the functions

- Documentation/ContentObjects/Image/Index.rst
- Documentation/Setup/Config/Index.rst
config.disableImgBorderAttr was removed as well
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/168
> [BEAKING] Remove border and longdescURL properties from IMAGE cObject

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
Sentences should start uppercase.
> Minor typo

- Documentation/Setup/Page/Index.rst
StyleSheets and JavaScripts should be stored in a site package extension and not on fileadmin.
> [TASK] Use site package path for examples

- Documentation/MenuObjects/Tmenu/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/228
> [BREAKING] #96517 - TMENU.collapse TypoScript removed

- Documentation/Setup/Config/Index.rst
There is no config setting for removing the website title from the title tag.  With this workaround you can remove the website title and keep the page title, that also can be set by PageTitleProviders.
> Add example to remove the website title

- Documentation/Conditions/Index.rst
POST arguments of forms do not work here.
> set example Url parameter without apostrophe

- Documentation/ContentObjects/Fluidtemplate/Index.rst
While both partialRootPath and partialRootPaths (mind the plural s) have been described ever since and also the layoutRootPath and layoutRootPaths, templateRootPath (sing) was missing. I added templateRootPath and made the difference to templateRootPaths (plural) more clear I hope.
Releases: main, 11.5, 10.4
> [BUGFIX] Add missing templateRootPath (sing) to FLUIDTEMPLATE

- Documentation/Functions/Data.rst
- Documentation/Functions/Stdwrap.rst
This is helpful when migrating to typo3/cms-composer-installers v4+.
Related: https://forge.typo3.org/issues/99203
> [TASK] Add example with path to stdWrap.insertData

- Documentation/Gifbuilder/Examples.rst
GMENU was removed in TYPO3 v10.0.
Additionally, fix a typo and link to IMAGE cObject.
> [TASK] Remove reference to GMENU

- Documentation/Setup/Config/Index.rst
- update the text
- drop the old overview table
- Insert another title level ('#######'), for contents reasons and to make the headlines of properties on that page smaller
This is what we get:
> Update introduction of page Setup/Config/Index.rst

- Documentation/Setup/Config/Index.rst
> [BUGFIX] Add missing header for config.additionalHeaders

- Documentation/Functions/Typolink.rst
The option was deprecated with v10 and removed in v11. Additionally, add an example for addQueryString.
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-93041-RemoveTypoScriptOptionAddQueryStringmethod.html
> [BREAKING] #93041 - Remove TypoScript option addQueryString.method

- Documentation/Functions/Typolink.rst
The option was deprecated with v10 and removed in v11. Additionally, add an example for addQueryString.
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-93041-RemoveTypoScriptOptionAddQueryStringmethod.html
> [BREAKING] #93041 - Remove TypoScript option addQueryString.method (#684)

- Documentation/Setup/Page/Index.rst
Dublin Core tags are not supported since the introduction of the Meta Tag API. Neither the core itself covers DC tags, nor does EXT:seo.
> Remove DC-tag example

- Documentation/Setup/Page/Index.rst
Dots have to be escaped, otherwise, the property will be ignored (To be exact: parsed TS could not be rendered in a correct way).
> Escape dot in key of meta-tag identifier (#689)

- .github/workflows/backport.yml
This avoids the errors when running with a backport tag in a PR:
"This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023."
"The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead."
> [CI] Update used Ubuntu version to "latest"

- Documentation/About.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/UsingSetting/Entering.rst
We now use the start label again to link to start pages
Related: TYPO3-Documentation/T3DocTeam#198
> Replace links to start page (:doc: => :ref:)

- Documentation/Conditions/Index.rst
`request` and `ip()` are moved from the "all contexts" into the "frontend context" and a "versionchanged" directive was added. I avoided the "deprecation" directive by intention as this may cause confusion by integrators not reading the whole sentence.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/376
Releases: main
> [DEPRECATION] #100047 - PageTsConfig and UserTsConfig must not rely on request

- Documentation/Functions/Stdwrap.rst
The stdWrap functions are executed in a specific order. The documentation of the functions reflects this order. The strtotime is called before the stfrtime.
See: https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L196-L199
> [BUGFIX] Switch stdWrap order of strtotime and stftime

- Documentation/Functions/Stdwrap.rst
The stdWrap functions are executed in a specific order. The documentation of the functions reflects this order. The strtotime is called before the stfrtime.
See: https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L196-L199
> [Backport 11.5] [BUGFIX] Switch stdWrap order of strtotime and strftime (#713)

- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/Setup/Config/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/395
Releases: main
> [FEATURE] #19856 - Set special ATagParams for links to access restricted pages

- Documentation/Functions/Data.rst
This is a preparation for upcoming deprecations of site language properties. A table is a mess to handle long text, so the properties are displayed as a list.
Additionally, link to the according TYPO3 Explained chapters for more information aboiut site configuration / site language configuration.
> [TASK] Use a list for site / site language properties

- Documentation/Conditions/Index.rst
With commit https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/commit/6b17a23e4d53494f9491f0372eb86204d864fb60 the deprecation notices for ip() and request() were removed. They have been restored with this PR.
Also, the deprecation notices of loginUser() and usergroup() have been adjusted.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/434
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/719
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/721
Releases: main
> [TASK] Restore deprecation notices for conditions

- Documentation/Setup/Config/Index.rst
Additionally, remove the note in config.doctype. In TypoScriptFrontendController the doctype is used, if xhtmlDoctype is not set. So the note is superfluous.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/438
Releases: main
> [TASK] #100461 - Deprecate TypoScript config.xhtmlDoctype

- Documentation/Conditions/Index.rst
Hello,
with following change:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100405-PropertyTypoScriptFrontendController-type.html
you can not access $TSFE->type anymore. That's why I have moved the example to the new request.getPageAttributes() location.
But be careful:
Doing so, will result in an Exception while opening the ExtensionManager. I already have added a forge ticket: https://forge.typo3.org/issues/100595
Stefan
> Move example with typeNum

- Documentation/TopLevelObjects/Module.rst
> [BUGFIX] Correct property name of features.skipDefaultArguments

- Documentation/Conditions/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/447
Releases: main
> [TASK] #100563 - Using null-safe-operator with getTSFE() function

- Documentation/Setup/Config/Index.rst
[11LTS docs for config.absRefPrefix](https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/Setup/Config/Index.html) states
`If the option config.forceAbsoluteUrls is enabled, absRefPrefix is overridden.`
However as [12LTS docs](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Setup/Config/Index.html#setup-config-forceabsoluteurls) state, `config.forceAbsoluteUrls`was introduced in 12.1, thus isn't available in 11
> 11LTS docs for config.absRefPrefix refer to 12LTS alternative

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
Attention should be used for caveats where things can go wrong.
> Use hint to hint at HMENU options

- Documentation/ContentObjects/Image/Index.rst
> [BUGFIX] Correct spelling of config.doctype

- Documentation/ContentObjects/Image/Index.rst
Additionally, correct the spelling of config.doctype.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/496
Releases: main
> [BUGFIX] Remove reference to obsolete config.xhtmlDoctype

- Documentation/ContentObjects/Fluidtemplate/Index.rst
As stated by Oliver Hader in the [forge issue](https://forge.typo3.org/issues/98200):
> Using stdWrap on declarative settings like paths, which are processed by other components (e.g. Fluid), is not a good idea...
> [TASK] #98200 Recommend conditions for rootPaths

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
I'm not quite sure here. But if I do understand the code correctly, the .dataProcessing subkey inside a FilesProcessor configuration is not interpreted (unlike DatabaseQueryProcessor). It wouldn't even be clear, how the resulting data would get passed alongside the fal objects.
> Remove .dataProcessing from FilesProcessor docs

- Documentation/Setup/Config/Index.rst
Added the `L` parameter to the list of parameters not to be included in `config.linkVars`. This affects all TYPO3 versions >= 9.5
> Update config.linkVars section

- Documentation/Setup/Config/Index.rst
Added the `L` parameter to the list of parameters not to be included in `config.linkVars`.
This affects all TYPO3 versions >= 9.5
----
backport of #764 (Torben Hansen PR)
> Update config.linkVars section (10.4 branch)

- Documentation/Setup/Config/Index.rst
Added the `L` parameter to the list of parameters not to be included in `config.linkVars`. 
This affects all TYPO3 versions >= 9.5
---- 
backport of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/764 (Torben Hansen PR)
> Update config.linkVars section (9.5 branch)

- Documentation/Functions/Select.rst
- Add small example for select.join.
- Improve explanatory text
Previously, the explanatory text was slightly misleading because it instructed to use the table name where in fact an entire join clause (without the word "JOIN") can be used including aliasing the table and adding a constraint with "ON".
> [Backport 11.5] Add example for select.join (#775)

- Documentation/Settings.cfg
Additionally, remove the outdated t3cheatsheets reference.
Releases: 12.4
> [TASK] Adjust links to manuals for v12.4

- Documentation/Functions/Select.rst
- replace linking to "select" (the same) page with link to CONTENT object type
- point out additional examples on CONTENT page because this contains several examples with select and more context
> Optimize the links on select page

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/_FilesProcessorFlexForm.typoscript
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/_FlexFormWithImage.xml
> [TASK] Add Example for FilesProcessor with a FlexForm file

- Documentation/Conditions/Index.rst
- Documentation/Functions/Data.rst
- "direction" and "twoLetterIsoCode" have been deprecated with v12.3
- "hreflang" has been changed with v12.4
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/362
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/365
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/583
> [TASK] Add deprecations and changes to site language (#782)

- Documentation/Setup/Page/Index.rst
As Twitter has been renamed to some random letter and the referenced style is not available anymore, another example is used.
> [TASK] Adjust external includeCSSLibs example

- Documentation/Setup/Page/Index.rst
As Twitter has been renamed to some random letter and the referenced style is not available anymore, another example is used.
> [Backport 11.5] [TASK] Adjust external includeCSSLibs example (#789)

- Documentation/Conditions/Index.rst
- Documentation/Functions/Data.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/584
Releases: main
> [TASK] Remove deprecated code in SiteLanguage

- Documentation/Functions/Stdwrap.rst
releases: main
Remark: In my opinion the "Example" and "Content-supplying properties" part, at the end of the site, should be moved back to the top, like in for example the 10.x version of the TYPO3 Documentation. Because if it is so far down, hardly anyone reads it, but especially the part with the order is very important. If you see this differently or have suggestions for improvement through mistakes, then let me know.
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Stdwrap.html
> Changing the order of the Content-supplying properties of stdWrap part

- Documentation/Setup/Page/Index.rst
Resolves: #788
Related: https://forge.typo3.org/issues/100954
> [BUGFIX] Configure additional attributes with "includeJS"

- Documentation/Conditions/Index.rst
Related: https://typo3.slack.com/archives/C025BQLFA/p1695726759085809
> [TASK] Check request object in conditions

- Documentation/Gifbuilder/ObjectNames/Index.rst
A PNG file is also possible at least since TYPO3 v11. Additionally, a JPG can either be configured with "jpg" or "jpeg".
> [TASK] Improve format description of GIFBUILDER

- Documentation/Functions/Data.rst
cObj, etc are under "Properties" and not equal to it. Additionally, the TOC has been moved into the Properties section.
> [BUGFIX] Correct header level in "Data / getText" chapter

- Documentation/Functions/Data.rst
cObj, etc are under "Properties" and not equal. Additionally, the TOC has been moved into the Properties section.
> [Backport 11.5] [BUGFIX] Correct header level in "Data / getText" chapter (#822)

- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
Proven by the example introduced with #824.
> [TASK] GIFBUILDER's TEXT.text property allows a fixed string

- Documentation/Settings.cfg
Only the main branch is relevant for the changelog. This change avoids the rendering error:
intersphinx inventory 'https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/objects.inv
Releases: 12.4, 11.5
> [BUGFIX] Use main branch for changelog docs

- Documentation/Settings.cfg
Only the main branch is relevant for the changelog. This change avoids the rendering error:
intersphinx inventory 'https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/objects.inv
Releases: 12.4, 11.5
> [BUGFIX] Use main branch for changelog docs (#840)

- Documentation/Gifbuilder/ObjectNames/Index.rst
The heading "Object names in this section" has a main drawback: When you are using the search you see the title and wonder: "what section". Now it is clear, which objects are meant.
> [TASK] Rename chapter "Object names in this section"

- Documentation/Gifbuilder/Examples.rst
The "gdlib_png" setting was removed in TYPO3 v13.0. PNG files are now always used instead of GIF.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/670
Releases: main
> [TASK] Remove outdated hint to activate GFX|gdlib_png

- Documentation/Gifbuilder/Calc.rst
- Documentation/Gifbuilder/Index.rst
Under the Gifbuilder folder there is another Gifbuilder folder with the introduction text. The first Gifbuilder folder holds only a TOC.
This patch changes that:
- The introduction text is moved to the start page.
- The text about +calc is moved parallel to the start page. This way it is more prominent as it is displayed in the navigation.
- The TOC now starts with the examples and the +calc chapter. So they are more prominent in the TOC. Then the object reference is following.
The link to the NonGifbuilderObject is a left-over: It was removed in a previous patch and forgotten to remove the link.
> [TASK] Dissolve Gifbuilder/Gifbuilder chapter

- Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
- Documentation/Settings.cfg
There was an ambiguous wording: "value" is a property, right. But the effects were also called "properties". This is now streamlined: effects are now called "effects".
- Add a TOC for the effects
- Add examples
> [TASK] Revise GIFBUILDER object EFFECT

- Documentation/Functions/Parsefunc.rst
"sword" is rendered wrong in the TOC here: https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/Functions/Parsefunc.html
> FIX: wrong level of 'sword' in TOC

- Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
> [BUGFIX] Add missing caption to GIFBUILDER's OUTLINE.color property

- Documentation/Setup/Page/Index.rst
Related: https://forge.typo3.org/issues/102327
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98312-TypoScriptSettingPageCSS_inlineStyleRemoved.html
> [TASK] #98312 - TypoScript setting page.CSS_inlineStyle removed

- Documentation/Gifbuilder/Examples.rst
- Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
- Documentation/Gifbuilder/ObjectNames/Box/Index.rst
- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
- Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
- Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Gifbuilder/Properties.rst
> [TASK] Use custom types for linking object properties in GIFBUILDER chapter

- Documentation/Functions/Stdwrap.rst
A label existed previously (stdwrap-addpagecachetags) and is still being referenced from TSconfig reference (see warnings).
> Add label for addPageCacheTags again

- Documentation/Gifbuilder/Properties.rst
Additionally, set the default format to "png" (since v13.0).
See: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/frontend/Classes/Imaging/GifBuilder.php#L1416-L1424
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/700
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/718
Releases: main
> [FEATURE] #102177 - Add WebP support for GIFBUILDER

- Documentation/Functions/Cache.rst
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/80527
The 12.4 backport should be delayed until December 12th, in order to wait for the 12.4.9 release that'll contain mentioned bugfix.
> Subpart cache tags are now being propagated to page cache tags

- Documentation/Gifbuilder/Examples.rst
- Documentation/Gifbuilder/ObjectNames/Adjust/Index.rst
- Documentation/Gifbuilder/ObjectNames/Box/Index.rst
- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Effect/Index.rst
- Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
- Documentation/Gifbuilder/ObjectNames/Emboss/Index.rst
- Documentation/Gifbuilder/ObjectNames/Image/Index.rst
- Documentation/Gifbuilder/ObjectNames/Outline/Index.rst
- Documentation/Gifbuilder/ObjectNames/Scale/Index.rst
- Documentation/Gifbuilder/ObjectNames/Shadow/Index.rst
- Documentation/Gifbuilder/ObjectNames/Text/Index.rst
- Documentation/Gifbuilder/ObjectNames/Workarea/Index.rst
- Documentation/Gifbuilder/Properties.rst
- Documentation/Settings.cfg
This eases the migration to the PHP-based documentation rendering.
> [TASK] Use confval instead of custom t3-gifbuilder-... directives (#915)

- Documentation/ContentObjects/ImgResource/Index.rst
Remove this note - this was a workaround from the old days and isn't in use anymore, especially with images being rendered using fluid or similar.
Releases: main
> [TASK] Avoid info about TSFE->lastImgResourceInfo

- Documentation/Setup/Config/Index.rst
- Remove temporal reference ("now", "unlike before") - as this setting was introduced long ago with TYPO3 v7
- Add link to logging chapter in TYPO3 Explained
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/3753
> [TASK] Streamline config.contentObjectExceptionHandler

- Documentation/UsingSetting/AddTypoScriptWithExtensions.rst
Additionally, remove the old link to changelog for the new syntax for importing TypoScript files.
> [TASK] Use captions for code snippets

- Documentation/Conditions/Index.rst
Additionally, fix some mix-ups with "Parameter" and "Type". Also, "Mixed" is used instead of "Custom" for data types.
> [Backport 11.5] [TASK] Replace "aspect" with confval in "Conditions" chapter (#930)

- Documentation/AppendixA/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/444
> [TASK] #100405 - Deprecate property TypoScriptFrontendController->type

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/CommaSeparatedValueProcessor.rst
- Documentation/Settings.cfg
Additionally:
- Named anchors have been added
- Data types (like string and integer) are linked
- The length of strings ("string(1)") is removed as there is no enforcement in the code
> [TASK] Replace "t3-data-processor-csv" with "confval"

- Documentation/AppendixA/Index.rst
The usage of `TSFE->getPageArguments()` is not recommended anymore as this method has been marked as internal for v13.0. Additionally, remove the internal knowledge, the migration of the request attribute should be enough for the average user.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/752
Releases: main
> [TASK] #102621 - TSFE->getPageArguments() marked as internal

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
- Documentation/Settings.cfg
Additionally:
- Data types (like string and integer) are linked
> [TASK] Replace "t3-data-processor-db" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-data-processor-files" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
- Documentation/Settings.cfg
> [Backport 12.4] [TASK] Replace "t3-data-processor-files" with "confval" (#952)

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
- Documentation/Settings.cfg
> [Backport 11.5] [TASK] Replace "t3-data-processor-files" with "confval" (#952) (#954)

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-data-processor-flex" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
- Documentation/Settings.cfg
> [Backport 12.4] [TASK] Replace "t3-data-processor-flex" with "confval" (#956)

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
- Documentation/Settings.cfg
> [Backport 11.5] [TASK] Replace "t3-data-processor-flex" with "confval" (#956)

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
- Documentation/Settings.cfg
Additionally:
- Data types (like string and integer) are linked
> [TASK] Replace "t3-data-processor-gallery" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/LanguageMenuProcessor.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-data-processor-lang" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
- Documentation/Settings.cfg
Additionally:
- Wrong data types are fixed (int -> bool, int -> string)
- Data types (like string, int, bool) are linked
> [TASK] Replace "t3-data-processor-menu" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteLanguageProcessor.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-data-processor-sitelang" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteProcessor.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-data-processor-site" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SplitProcessor.rst
- Documentation/Settings.cfg
Additionally:
- Data types (like string, bool) are linked
- Boolean types are corrected, "0" or "1" is necessary instead of "false" or "true"
> [TASK] Replace "t3-data-processor-split" with "confval"

- Documentation/ContentObjects/Text/Index.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Settings.cfg
Additionally:
- Some references added
- Mark SQL fields/HTML tags with corresponding role
> [TASK] Replace "t3-cobj-text" with "confval"

- Documentation/ContentObjects/Text/Index.rst
- Documentation/Settings.cfg
Additionally:
- Some references added
- Mark SQL fields/HTML tags with corresponding role
> [Backport 11.5] [TASK] Replace "t3-cobj-text" with "confval" (#976)

- Documentation/ContentObjects/CoaAndCoaInt/Index.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-cobj-coa" with "confval"

- Documentation/ContentObjects/Case/Index.rst
- Documentation/ContentObjects/CoaAndCoaInt/Index.rst
- Documentation/Settings.cfg
Additionally:
- Fix wrong references in COA chapter which were missed in a previous change
> [TASK] Replace "t3-cobj-case" with "confval"

- Documentation/ContentObjects/Content/Index.rst
- Documentation/Settings.cfg
Additionally:
- Missing named anchors are added
- Data types (like integer, boolean) are linked
- Use definition list for possible values of "slide" property
> [TASK] Replace "t3-cobj-content" with "confval"

- Documentation/ContentObjects/Content/Index.rst
- Documentation/Settings.cfg
Additionally:
- Missing named anchors are added
- Data types (like integer, boolean) are linked
- Use definition list for possible values of "slide" property
> [Backport 11.5] [TASK] Replace "t3-cobj-content" with "confval" (#985)

- Documentation/ContentObjects/Extbaseplugin/Index.rst
- Documentation/Settings.cfg
Additionally:
- Link to Extbase introduction
> [TASK] Replace "t3-cobj-extbaseplugin" with "confval"

- Documentation/ContentObjects/Files/Index.rst
- Documentation/Settings.cfg
Additionally:
- Link to FAL page
- Data types (like string, integer) are linked
> [TASK] Replace "t3-cobj-files" with "confval"

- Documentation/ContentObjects/Fluidtemplate/DataProcessing.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/Settings.cfg
Additionally:
- Link to Fluid page
- Data types (like string, path) are linked
- Use "my_extension" instead of "some_extension"
> [TASK] Replace "t3-cobj-fluidtemplate" with "confval"

- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/Settings.cfg
Additionally:
- Data types (like integer, string, boolean) are linked
> [TASK] Replace "t3-cobj-hmenu" with "confval"

- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/Settings.cfg
Additionally:
- Data types (like integer, string, boolean) are linked
> [Backport 11.5] [TASK] Replace "t3-cobj-hmenu" with "confval" (#996)

- Documentation/ContentObjects/ImgResource/Index.rst
- Documentation/Settings.cfg
Additionally:
- Anchors added where missing
- Data types (imgResource) are linked
> [TASK] Replace "t3-cobj-img-resource" with "confval"

- Documentation/ContentObjects/LoadRegister/Index.rst
- Documentation/Settings.cfg
Additionally:
- Data type (string) are linked
- Field names in the text are marked as TypoScript
> [TASK] Replace "t3-cobj-load-register" with "confval"

- Documentation/TopLevelObjects/Index.rst
- Documentation/TopLevelObjects/Other.rst
This one is declared 'internal' in the docs
already and may be removed in v13. There is
no point in documenting this core internal
structure. The 'plaintext' hint is wrong.
> [TASK] Avoid 'types' TLO

- Documentation/Setup/Config/Index.rst
This is a preparation for upcoming adjustments.
The indentation of the "container" directives are not adapted for now. In a follow-up they are converted to a "confval".
> [TASK] Adjust indentation on "CONFIG & config" chapter

- Documentation/Setup/Config/Index.rst
The indentation of the "container" directives are not adjusted for now. In a follow-up they are converted to a "confval".
> [Backport 12.4] [TASK] Adjust indentation on "CONFIG & config" chapter (#1025)

- Documentation/Setup/Config/Index.rst
The indentation of the "container" directives are not adjusted for now. In a follow-up they are converted to a "confval".
> [Backport 11.5] [TASK] Adjust indentation on "CONFIG & config" chapter (#1025)

- Documentation/ContentObjects/Hmenu/Rootline.rst
- Documentation/Functions/Replacement.rst
- Documentation/Functions/Split.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/Settings.cfg
- Documentation/Setup/Page/Examples.rst
- Documentation/Setup/Page/Index.rst
- Documentation/TopLevelObjects/Plugin.rst
- Documentation/UsingSetting/Debugging.rst
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.typo3.org/m/typo3/book-extbasefluid/11.5/en-us/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.typo3.org/m/typo3/book-extbasefluid/11.5/en-us/objects.inv
./Documentation/ContentObjects/Hmenu/Rootline.rst:95: ERROR: Unknown interpreted text role "t3-menu-tmenu".
./Documentation/ContentObjects/Fluidtemplate/Index.rst:33: WARNING: undefined label: t3viewhelper:cobject_data
./Documentation/ContentObjects/Fluidtemplate/Index.rst:46: WARNING: undefined label: t3viewhelper:typo3fluid-fluid-debug
./Documentation/ContentObjects/Fluidtemplate/Index.rst:114: WARNING: undefined label: …
> [BUGFIX] Remove some rendering warnings

- Documentation/Conditions/Index.rst
Related: https://forge.typo3.org/issues/102891
> [BUGFIX] #102891 - Use traverse for request.getParsedBody()

- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/Settings.cfg
Additionally:
- "Order of priority" is now a list for better readability
- Data types (boolean) are linked
> [TASK] Replace "t3-menu-tmenu-state" with "confval"

- Documentation/ContentObjects/Hmenu/Rootline.rst
- Documentation/MenuObjects/Tmenu/Index.rst
- Documentation/Settings.cfg
Additionally:
- Data types (boolean, integer, string) are linked
> [TASK] Replace "t3-menu-tmenu" with "confval"

- Documentation/Functions/Cache.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-cache" with "confval"

- Documentation/Functions/Encapslines.rst
- Documentation/Settings.cfg
Additionally:
- Data types (string) are linked
> [TASK] Replace "t3-function-encapslines" with "confval"

- Documentation/Functions/Typolink.rst
- Documentation/Settings.cfg
Additionally:
- Data types (integer, string) are linked
- Output format in example of code-block for text has been corrected
> [TASK] Replace "t3-typolink-handler" with "confval"

- Documentation/Functions/Typolink.rst
- Documentation/Settings.cfg
Additionally:
- Data types (target, wrap, string, integer) are linked (where missing)
> [TASK] Replace "t3-function-typolink" with "confval"

- Documentation/Functions/HtmlparserTags.rst
- Documentation/Settings.cfg
Additionally:
- Add anchors
- Avoid aspect role for example as it is a left-over from switching to "t3-function-htmlparser-tags" in the past.
> [TASK] Replace "t3-function-htmlparser-tags" with "confval"

- Documentation/Functions/Htmlparser.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-htmlparser" with "confval"

- Documentation/Functions/Imgresource.rst
- Documentation/Settings.cfg
Additionally:
- Use modern file type in example (png instead of gif)
> [TASK] Replace "t3-function-imgresource" with "confval"

- Documentation/Functions/Numberformat.rst
- Documentation/Settings.cfg
> [TASK] Replace "t3-function-numberformat" with "confval"

- Documentation/Functions/Numrows.rst
- Documentation/Settings.cfg
Additionally:
- Indentations are adjusted
- Role `sql` is used where appropriate
> [TASK] Replace "t3-function-numrows" with "confval"

- Documentation/Conditions/Index.rst
Sphinx is here lax and looks, if there is a reference of that name in all of the intersphinxes. But guides is more picky and throws a warning. Therefore, the reference is now prefixed with the correct manual.
> [BUGFIX] Correct reference to TYPO3_CONF_VARS['SYS'] chapter in TYPO3 Explained

- Documentation/Conditions/Index.rst
Sphinx is in this case lax and looks, if there is a reference of that name in all of the intersphinxes. But guides is more strict and throws a warning. Therefore, the reference is now prefixed with the correct manual.
> [BUGFIX] Correct reference to backend layout chapter in TYPO3 Explained

- Documentation/Functions/Parsefunc.rst
- Documentation/Settings.cfg
> [Backport 12.4] [TASK] Replace "t3-function-parsefunc" with "confval" (#1094)

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
- Documentation/Introduction/Index.rst
- Documentation/TopLevelObjects/Module.rst
Sphinx is here lax and looks, if there is a reference of that name in all of the intersphinxes. But guides is more picky and throws a warning. Therefore, the reference is now prefixed with the correct manual.
> [BUGFIX] Correct more references

- Documentation/Introduction/Index.rst
- Documentation/TopLevelObjects/Module.rst
Sphinx is here lax and looks, if there is a reference of that name in all of the intersphinxes. But guides is more picky and throws a warning. Therefore, the reference is now prefixed with the correct manual.
> [BUGFIX] Correct more references (#1107)

- Documentation/Functions/Split.rst
- Documentation/Settings.cfg
Additionally:
- Correct index and anchor for properties
> [TASK] Replace "t3-function-split" with "confval"

- Documentation/Functions/Typolink.rst
Initially this feature added `rel="noopener noreferrer`. However `noreferrer` also implies the property `noopener`. Therefore, the later was removed.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/867
> [BUGFIX] Remove noopener as superfluous

- Documentation/Functions/Typolink.rst
Initially this feature added `rel="noopener noreferrer`. However `noreferrer` also implies the property `noopener`. Therefore, the later was removed.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/867
> [Backport 11.5] [BUGFIX] Remove noopener as superfluous (#1113)

- Documentation/ContentObjects/Hmenu/Categories.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
- Documentation/Functions/Data.rst
- Documentation/Functions/Encapslines.rst
- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Select.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Settings.cfg
- Documentation/Setup/Config/Index.rst
- Documentation/UsingSetting/Debugging.rst
- Documentation/UsingSetting/Register.rst
Additionally:
- Use "t3src" to link directly to a Core file
- Adjust header level according to https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/CheatSheet.html#headlines
> [TASK] Replace "t3-function-stdwrap" with "confval"

- Documentation/ContentObjects/Fluidtemplate/Index.rst
According to https://forge.typo3.org/issues/102315 it is no longer possible to skip the argument `extensionName` in the ViewHelpers f:translate and f:uri.resource with the property `extbase.controllerExtensionName` as of TYPO3 v12. For this reason, the use of this property should no longer be used as a tip in the documentation. Instead, a warning should be issued.
> [TASK] Update property information

- Documentation/Functions/Strpad.rst
- Documentation/Settings.cfg
Additionally:
- Link directly to php.net chapter for str_pad() method for more information
> [TASK] Replace "t3-function-strpad" with "confval"

- Documentation/Setup/Config/Index.rst
> [BUGFIX] Correct outdated reference to typolink/forceAbsoluteUrl

- Documentation/Functions/Parsefunc.rst
> [BUGFIX] Correct example about parseFunc.short

- Documentation/Conditions/Index.rst
Remove the reference to the null-safe operator. The operator has been introduced in Symfony 6, but TYPO3 11 still uses Symfony 5.
> [BUGFIX] Remove reference to null-safe operator in TYPO3 v11

- .gitignore
Most recent versions of ddev seem to not create their own gitignore anymore
> [TASK] Add ddev directory to gitignore

- Documentation/ContentObjects/Fluidtemplate/DataProcessing/CommaSeparatedValueProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FilesProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/FlexFormProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/GalleryProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/LanguageMenuProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/MenuProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteLanguageProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SiteProcessor.rst
- Documentation/ContentObjects/Fluidtemplate/DataProcessing/SplitProcessor.rst
Add missing anchors and headlines
> [TASK] Set unique names for confvals in Dataprocessor chapter

- Documentation/ContentObjects/Case/Index.rst
- Documentation/ContentObjects/CoaAndCoaInt/Index.rst
- Documentation/ContentObjects/Content/Index.rst
- Documentation/ContentObjects/Extbaseplugin/Index.rst
- Documentation/ContentObjects/Files/Index.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/Hmenu/Index.rst
- Documentation/ContentObjects/Image/Index.rst
- Documentation/ContentObjects/ImgResource/Index.rst
- Documentation/ContentObjects/LoadRegister/Index.rst
- Documentation/ContentObjects/Records/Index.rst
- Documentation/ContentObjects/Svg/Index.rst
- Documentation/ContentObjects/Text/Index.rst
- Documentation/ContentObjects/UserAndUserInt/Index.rst
> [TASK] Set unique names for confvals in cobjects chapter

- Documentation/Setup/Config/Index.rst
Replace aspect table with confval where not yet happened.
Use unified names
We should have a look at the default values in a follow up. Some are missing, some are integers for type boolean.
> [TASK] Unify confvals for config section

- Documentation/Conditions/Index.rst
A condition consists not only of the - well - condition itself, but also the marking of the end of a condition is important. This is now added, some examples already have the end marker.
> [TASK] Show full conditions in examples

- Documentation/TopLevelObjects/Module.rst
* Use confvals instead of tables
* Give headlines to examples
* Introduce a toc for the properties
> [TASK] Overhaul module chapter

- Documentation/ContentObjects/Hmenu/Updated.rst
> [TASK] Overhaul HMENU updated page

- Documentation/ContentObjects/Fluidtemplate/Index.rst
This removes a blank line which caused a wrong output in the documentation. Without this blank line the text should not go into a new block.
> Removed unnecessary new line

- Documentation/Setup/Page/Index.rst
Use the same Markup syntax for "defer" property in `includeJS` paragraph as for other option flags. Previously it was easily overlooked, because the "defer" option was not printed bold and its description was not in a newline below the bold text.
> Fix markup for defer (#1215)

- Documentation/ContentObjects/Extbaseplugin/Index.rst
- Documentation/ContentObjects/Files/Index.rst
- Documentation/ContentObjects/Fluidtemplate/Index.rst
- Documentation/ContentObjects/Image/Index.rst
- Documentation/ContentObjects/ImgResource/Index.rst
- Documentation/ContentObjects/Svg/Index.rst
since https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.4/Feature-64200-AllowIndividualContentCaching.html
Every content object supports cache property.
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/237
> [BUGFIX] Add missing cache property to content elements

- Documentation/DataTypes/Index.rst
- Documentation/Functions/Htmlparser.rst
- Documentation/Functions/OptionSplit.rst
- Documentation/Gifbuilder/ObjectNames/Crop/Index.rst
- Documentation/Gifbuilder/ObjectNames/Ellipse/Index.rst
- Documentation/Setup/Page/Index.rst
They cause warnings since the newest version of the render-guides
> [BUGFIX] Resolve duplicate link anchors

- Documentation/ContentObjects/Pageview/Index.rst
I decided to reorder the examples to a dedicated examples section. From each property / variable I link to the example. The advantage is, that we can use the same example for several properties or the same property with several examples.
Also the properties section is less cluttered.
> [TASK] PAGEVIEW with confval tables

- Documentation/TopLevelObjects/Page/Index.rst
`includeJS` instead of `includeCSSLibs` is demonstrated - links were set correctly
> fix typo with includeJS / includeCSSLibs

- Documentation/TopLevelObjects/Page/Index.rst
As described in #1258 there is some inconsistency between source-code and documentation.
For now documentation should reflect current state of sourcecode until a core-patch is developed and merged
> [TASK] match includeJS documentastion to sourcecode

- Documentation/TopLevelObjects/Page/Index.rst
* [TASK] adjust documentation to current behaviour
Currently RequestHandler handles includeJS/includesJSFooter and includeJSLibs/includeJSFooterlibs differently. In the libs-part there is no data-array but all parameters not explicitly defined are passed through as they are. This only relates to includeJS*
* [TASK] add hint about includeCSS
* Update Documentation/TopLevelObjects/Page/Index.rst
---------
> [BACKPORT] match includeJS documentastion to sourcecode (#1259)

- .github/workflows/tests.yml
- Build/.gitignore
- Build/.php-cs-fixer.dist.php
- Build/Scripts/runTests.sh
- Documentation/CodeSnippets/Config/DataProcessing.php
- Documentation/CodeSnippets/Config/Menus.php
- Documentation/UsingSetting/_Sets/_TcaOverridesSystemplateV12.php
- Documentation/UsingSetting/_Sets/_ext_localconf.php
- Documentation/codesnippets.php
- Makefile
- composer.json
Following the scheme provided by @sbuerk
This change introduces `Build/Scripts/runTests.sh` execution wrapper in line with current TYPO3
Core implementation.
We introduce cgl and linting tests for code includes. And apply cgl.
I will backport this manually
> [TASK] Introduce `Build/Scripts/runTests.sh`

- .github/workflows/tests.yml
- Build/.gitignore
- Build/.php-cs-fixer.dist.php
- Build/Scripts/runTests.sh
- Documentation/CodeSnippets/Config/DataProcessing.php
- Documentation/CodeSnippets/Config/Menus.php
- Documentation/codesnippets.php
- Makefile
- composer.json
Following the scheme provided by @sbuerk
This change introduces `Build/Scripts/runTests.sh` execution wrapper in line with current TYPO3
Core implementation.
We introduce cgl and linting tests for code includes. And apply cgl.
> [BACKPORT 12.4][TASK] Introduce `Build/Scripts/runTests.sh`

- Documentation/Functions/HtmlparserTags.rst
This fix is only necessary for the 11.5 branch.
In newer branches `prefixLocalAnchors` isn't present anymore and in older branches, everything is fine.
> [TASK] Fix headline level for prefixLocalAnchors

- Documentation/Functions/GetEnv.rst
Add information, that a similar condition is written in lowercase not camelcase.
> Add Note regarding similar condition.

- Documentation/Functions/Parsefunc.rst
- Documentation/Functions/Typolink.rst
- Documentation/Functions/_Examples/Typolink-Example.rst
- Documentation/Functions/_StdWrap/_UserFunc.php
- Documentation/Functions/_StdWrap/_UserFunc.typoscript
- Documentation/Functions/_StdWrap/_UserFuncSimple.php
According to  https://review.typo3.org/c/Packages/TYPO3.CMS/+/72999 the userFunc now must return an instance of `LinkResultInterface`.
(drive-by fix of a few wrong formattings)
Closes #1275
> [TASK] Properly document typolink.userFunc usage

- Documentation/Functions/Parsefunc.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/958
releases: main
> [FEATURE] Make parseFunc allowTags and denyTags optional

- Documentation/Functions/Imgresource.rst
references: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/875
releases: main
> Feature: #93942 - Crop SVG images natively

- Documentation/Conditions/Index.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/925
> [TASK] Clarify constants do not work in constant conditions

- Documentation/TopLevelObjects/Module.rst
References: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96812-NoFrontendTypoScriptBasedTemplateOverridesInTheBackend.html#breaking-96812-no-frontend-typoscript-based-template-overrides-in-the-backend
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/1300
> [TASK] No Frontend TypoScript based template overrides in the backend

- Documentation/TopLevelObjects/Config.rst
- Documentation/TopLevelObjects/_includes/_concat-compress.rst.txt
The internal TYPO3 concatenation and compression comes with some drawbacks, also mentioned in https://forge.typo3.org/issues/75127.
This patch adds a "hint" to the four options to describe also disadvantages of using the options.
> [TASK] Add hint to concatenate/compress options

- Documentation/TopLevelObjects/Config.rst
Thanks @agriaIT for catching this!
Next time you can also try to use the "Edit on GitHub" button and propose the change directly, see https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Howto/EditOnGithub.html
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues/1315
> [BUGFIX] use spamProtectEmailAddresses_atSubst

- Documentation/TopLevelObjects/Config.rst
Setting a TypoScript option to `false` does not really disable the option, as it is casted to bool later on. `true` casts to true, which is correct, but for consistency reasons, we should always use `0` and `1` in TypoScript for boolean values.
See also: https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/DataTypes/Index.html#boolean
> [TASK] Use `0` and `1` for boolean values of config object

- Documentation/ContentObjects/Pageview/Index.rst
This change changed https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103504-NewContentObjectPageView.html
to remove the support for lowercase template path names.
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/904 
References:https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1005 
Releases: main
> [TASK] Lower case template path names have been removed

- Documentation/Functions/Select.rst
The new `\TYPO3\CMS\Core\Domain\Repository\PageRepository::getDescendantPageIdsRecursive()` introduced in v12 exits for `$startPageId=0` via early-return without resolving the recursion.
> Note on not resolving the recursion for “root”

- Documentation/TopLevelObjects/Page/Index.rst
The Open Graph meta tag examples are polluted by the meta refresh example. This is now moved to the already available section.
The previous "[seconds]; [URL, leave blank for same page]" is removed as this is not a manual about the "refresh" property, but about setting that property in TYPO3.
> [TASK] Move page.meta refresh example to dedicated section

- Documentation/Functions/Stdwrap.rst
> [BUGFIX] Move example output for formattedDate out of code block

- Documentation/Functions/Typolink.rst
Tested with this snippet in main and v12:
page.20 = TEXT
page.20.value = link to example.com
page.20.typolink.parameter = https://example.com/
> [BUGFIX] Adjust default value for typolink extTarget

- Documentation/Functions/Stdwrap.rst
An example for a custom date/time format derived from a timestamp has been added as a showcase.
Additionally, add a heading for each example to improve readability.
> [TASK] Improve stdWrap.formattedDate

- Documentation/TopLevelObjects/Page/Index.rst
> [TASK] Add full stdWrap example for page.meta

- Documentation/DataProcessing/_PageContentFetchingProcessor/_Default.html
Accessing the data does not work with contentElement.data.[property], but directly with contentElement.[property] (Tested in TYPO3 version 13.4.0-dev)
> [BUGFIX] Remove unnecessary “data.” in _Default.html

- Documentation/ContentObjects/Extbaseplugin/Index.rst
- Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_MyController.php
- Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_SomeTemplate.html
- Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_configurePlugin.php
- Documentation/ContentObjects/Extbaseplugin/_CodeSnippets/_libMyPlugin.typoscript
> [TASK] Add example: Display an Extbase plugin in a Fluid template

- Documentation/DataProcessing/CommaSeparatedValueProcessor.rst
- Documentation/DataProcessing/CustomDataProcessors.rst
- Documentation/DataProcessing/DatabaseQueryProcessor.rst
- Documentation/DataProcessing/FilesProcessor.rst
- Documentation/DataProcessing/FlexFormProcessor.rst
- Documentation/DataProcessing/GalleryProcessor.rst
- Documentation/DataProcessing/Index.rst
- Documentation/DataProcessing/LanguageMenuProcessor.rst
- Documentation/DataProcessing/MenuProcessor.rst
- Documentation/DataProcessing/PageContentFetchingProcessor.rst
- Documentation/DataProcessing/RecordTransformationProcessor.rst
- Documentation/DataProcessing/SiteLanguageProcessor.rst
- Documentation/DataProcessing/SiteProcessor.rst
- Documentation/DataProcessing/SplitProcessor.rst
- Documentation/TopLevelObjects/Config.rst
* Move versionadded directive for alias to top. Will be removed from main and 13.4 in a follow up.
* Mention FQN when introducing the data processor
* Restructure menu and headlines for easier readability
> [TASK] Display data processor aliases more prominent

- Documentation/AppendixA/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1074
> [TASK] #105230 - Declare TypoScriptFrontendController deprecated

- Documentation/Functions/Data.rst
Replacement for siteLanguage.twoLetterIsoCode and the new subkeys for siteLanguage.locale are now in the documentation.
Sources: typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php from main branch and https://review.typo3.org/c/Packages/TYPO3.CMS/+/77597
> Add new subkeys for siteLanguage.locale in Data.rst

- Documentation/Functions/Data.rst
Replacement for siteLanguage.twoLetterIsoCode and the new subkeys for siteLanguage.locale are now in the documentation.
Sources: typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php from main branch and https://review.typo3.org/c/Packages/TYPO3.CMS/+/77597
Preport into main of #1373
Needs to be backported to 13.4
> Add new subkeys for siteLanguage.locale in Data.rst (#1373)

- Documentation/TopLevelObjects/Other.rst
styles. is not unset after parsing since v7:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/31814
> [BUGFIX] Avoid hint to temp. in styles. TLO

- Documentation/TopLevelObjects/Index.rst
- Documentation/TopLevelObjects/Other.rst
Since TYPO3 v12, no unset() is executed when "temp." is parsed. So there is no longer any difference between addressing "temp." by reference or by copy.
> Remove the section for the TLO “temp.” as no unset() is executed anymore

- Documentation/About.rst
- Documentation/Functions/Stdwrap.rst
- Documentation/Functions/Typolink.rst
- Documentation/Guide/Index.rst
- Documentation/Index.rst
- Documentation/Syntax/Conditions/Index.rst
- Documentation/Syntax/FileImports/Index.rst
- Documentation/TopLevelObjects/Module.rst
- Documentation/UserTsconfig/Options.rst
- Documentation/UsingSettingTSconfig/_PageTSconfig/_pages.php
- Documentation/UsingSettingTSconfig/_PhpApi/_MyBackendLoggedInController.php
> [TASK] Change references previously going to tsconfig

- Documentation/Gifbuilder/Examples.rst
- Documentation/Gifbuilder/Properties.rst
- Documentation/Gifbuilder/_snippets/_avif.typoscript
- Documentation/UsingSettingTSconfig/_PageTSconfig/_pages.php
- Documentation/UsingSettingTSconfig/_PhpApi/_MyBackendLoggedInController.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1050
> [FEATURE] Add support for AVIF files in GIFBuilder

- Documentation/ContentObjects/Hmenu/Tmenu/Index.rst
This PR adds a notice to the TMENU documentation to outline, that `stdWrap.htmlSpecialChars = 1` should be used in order to prevent XSS vulnerabilities in TMENU items.
> Add notice about preventing XSS in TMENU

- Documentation/Introduction/Index.rst
> [TASK] Update introduction

- Documentation/TopLevelObjects/Page/Index.rst
Currently, they are linked to the "Properties" heading instead of the according section. Sadly, no warning about wrong refs was emitted during rendering.
> fix: correct anchors in PAGE properties

- Documentation/PageTsconfig/Mod/WebList.rst
> [TASK] Document page TSconfig setting mod.web_list.disableSearchBox #1474

- Documentation/PageTsconfig/Mod/WebList.rst
The superfluous backtick between `Default` and the description displays the first paragraph of the description in the default section.
> fix: correct display of itemsLimitPerTable

- Documentation/TopLevelObjects/Config.rst
Got probably merged accidentally with:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/commit/d2a0a9754758fea16b729ac2cd3f236d37e0f5e1
> [BUGFIX] Remove a 13.x feature from the 12.4 docs

- Documentation/ContentObjects/Fluidtemplate/_includes/_templateNameAutomatic.typoscript
`templateName` is of type string/stdWrap.
However, the snippet gives the impression that it is a cObject due to `templateName = TEXT`.
Working:
```
templateName = Default
```
Working
```
templateName.stdWrap.cObject = TEXT
templateName.stdWrap.cObject.value = Default
```
*Not* working
```
templateName= TEXT
templateName.value = Default
```
> [BUGFIX] Do not pretend to be a cObject

- Documentation/PageTsconfig/TceMain.rst
Headline says that the following example does not allow deletion, desxription says that this code snippet will allow deletion (which is true).
> [BUGFIX] Align headline and description in example

- Documentation/Index.rst
- Documentation/TopLevelObjects/Config.rst
- Documentation/TopLevelObjects/Index.rst
- Documentation/TopLevelObjects/Page/Index.rst
- Documentation/TopLevelObjects/PageAndConfig.rst
The page is the starting point for whatever rendering is configured via TypoScript. It is hard to find within the "Top level object."
The TypoScript config also has a central and special handling.
Leave hints of how they can be found in the previous place in the Top Level objects
> [TASK] Display page and config on top level of Frontend TypoScript

- Documentation/ContentObjects/Pageview/Index.rst
I just try to get PAGEVIEW running and get errors like:
Tried resolving a template file for controller action "Default->Pages/Default" in format ".html", but none of the paths contained the expected template file (Default/Pages/Default.html).
That's why I would prefer to provide a running example in first section, before we start explaining the containing variables for Fluid templating.
> Add section about Template naming and locations to PAGEVIEW

- Documentation/ContentObjects/Pageview/_includes/_PageWithConstant.html
With the example above, it should be uids
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/ContentObjects/Pageview/Index.html#cobj-pageview-data-settings-example
> typo in TypoScript

- Documentation/TopLevelObjects/Config.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1217
Releases: main
> [FEATURE] Add stdWrap to htmlTag.attributes

- Documentation/ContentObjects/Pageview/Index.rst
Examples are currently located under properties, which is not correct. The examples should be on the same level as properties.
> adjust header level of examples on PAGEVIEW page

- Documentation/TopLevelObjects/Config.rst
Although the link is given directly in the confval it is easier for users to just click on the link instead scrolling up and click (if you know already that there is a link above).
> Link examples to cache configuration from text

- Documentation/TopLevelObjects/Page/Index.rst
If you click on the link setup-page-bodyTag`, then you come to bodyTagCObject back again. This is misleading. You need to come to bodyTag.
bodyTagCObject
:name: page-bodyTagCObject
:type: cObject
This is the default body tag. It is overridden by :ref:`setup-page-bodyTag`
> setup-page-bodyTag should not point to Properties

- Documentation/Functions/Parsefunc.rst
There is no necessity anymore for user functions to be prepended with `user_` anymore, so that confusing and vague sentence can be removed.
> [DOCS] Remove outdated paragraph

- Documentation/Functions/Htmlparser.rst
Resolves: TYPO3-Documentation/Changelog-To-Doc#1067
> [TASK] Describe "removeTags" configuration possibilities

- Documentation/Conditions/Index.rst
- Documentation/PageTsconfig/Rte.rst
> [TASK] Use of siteLanguage(“locale”) corrected

- .github/workflows/tests.yml
The ergebnis/composer-normalize plugin still requires localheinz/diff, which conflicts with sebastian/diff and causes fatal errors in CI. Temporarily disable the composerNormalize step in runTests until upstream resolves the dependency issue.
> [BUGFIX] ci: disable composer-normalize step due to dependency conflict

- Documentation/Conditions/Index.rst
- Documentation/Syntax/Conditions/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1327
Releases: main
> [!!!][TASK] Remove TypoScript getTSFE() condition function
